# 1　データ整形：モデル前データまで

## 準備

In [1]:
from pathlib import Path
import pandas as pd
import os
import numpy as np
from tqdm import tqdm
from xml.etree.ElementTree import fromstring, ElementTree
from Evtx.Evtx import Evtx
import csv

In [2]:
%load_ext autoreload
%autoreload 2
import preprocess
import main

/home/siwamura/My_lad/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
INTERIM_DIR = Path('../data/interim')
PROCESSED_DIR = Path('../data/processed')
RAW_DIR = Path('../data/raw')
NO_MEANING_DIR = Path('../data/no_meaning')

## 1-1 AtomicRT（T1105）

### processed 作成（使用特徴量：EventId, deltaT）

In [ ]:
input_dir = INTERIM_DIR/project_name
output_dir = PROCESSED_DIR/project_name

In [ ]:
df = pd.read_csv(input_dir / f'{file_name}_prepared_structured.csv')

# 諸操作
df["Label"] = df["Label"].apply(lambda x: int(x != "-"))
df["datetime"] = pd.to_datetime(df["Timestamp"], format="%Y-%m-%d %H:%M:%S.%f %z")
df["timestamp"] = df["datetime"].view("int64") // 10**9  
df["deltaT"] = df["datetime"].diff().dt.total_seconds().fillna(0)

/home/siwamura/lad2/src_/ipykernel_1245661/1067428620.py:6: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  df["timestamp"] = df["datetime"].view("int64") // 10**9

In [ ]:
def sliding_window(raw_data, para):
    """
    split logs into sliding windows/session
    :param raw_data: dataframe columns=[timestamp, label, eventid, time duration]
    :param para:{window_size: seconds, step_size: seconds}
    :return: dataframe columns=[eventids, time durations, label]
    """
    log_size = raw_data.shape[0]
    label_data, time_data = raw_data.iloc[:, 1], raw_data.iloc[:, 0]
    logkey_data, deltaT_data = raw_data.iloc[:, 2], raw_data.iloc[:, 3]
    new_data = []
    start_end_index_pair = set()

    start_time = time_data[0]
    end_time = start_time + para["window_size"]
    start_index = 0
    end_index = 0

    # get the first start, end index, end time
    for cur_time in time_data:
        if cur_time < end_time:
            end_index += 1
        else:
            break

    start_end_index_pair.add(tuple([start_index, end_index]))

    # move the start and end index until next sliding window
    num_session = 1
    while end_index < log_size:
        start_time = start_time + para["step_size"]
        end_time = start_time + para["window_size"]
        for i in range(start_index, log_size):
            if time_data[i] < start_time:
                i += 1
            else:
                break
        for j in range(end_index, log_size):
            if time_data[j] < end_time:
                j += 1
            else:
                break
        start_index = i
        end_index = j

        # when start_index == end_index, there is no value in the window
        if start_index != end_index:
            start_end_index_pair.add(tuple([start_index, end_index]))

        num_session += 1
        if num_session % 1000 == 0:
            print("process {} time window".format(num_session), end="\r")

    for start_index, end_index in start_end_index_pair:
        dt = deltaT_data[start_index:end_index].values
        dt[0] = 0
        new_data.append(
            [
                time_data[start_index:end_index].values,
                max(label_data[start_index:end_index]),
                logkey_data[start_index:end_index].values,
                dt,
            ]
        )

    assert len(start_end_index_pair) == len(new_data)
    print(
        "there are %d instances (sliding windows) in this dataset\n"
        % len(start_end_index_pair)
    )
    return pd.DataFrame(new_data, columns=raw_data.columns)

# dfをdeeplog_fileに変換
def deeplog_file_generator(filename, df, features):
    with open(filename, "w") as f:
        for _, row in df.iterrows():
            for val in zip(*row[features]):
                f.write(",".join([str(v) for v in val]) + " ")
            f.write("\n")

In [ ]:
window_size = 5
step_size = 1

# sampling with sliding window
deeplog_df = sliding_window(
    df[["timestamp", "Label", "EventId", "deltaT"]],
    para={"window_size": int(window_size) * 60, "step_size": int(step_size) * 60},
)

there are 820 instances (sliding windows) in this dataset

In [ ]:
# normalとabnormalを切り分け
df_normal = deeplog_df[deeplog_df["Label"] == 0]
df_abnormal = deeplog_df[deeplog_df["Label"] == 1]

df_normal = df_normal.sample(frac=1, random_state=12).reset_index(
    drop=True
)  # shuffle
normal_len = len(df_normal)

In [ ]:
df_abnormal

Empty DataFrame
Columns: [timestamp, Label, EventId, deltaT]
Index: []

##### train_ratio = 40%, 60%, 80%

In [ ]:
# 案１（ファイル名を分けない）
train_ratio_list = [0.4, 0.6, 0.8]
for train_ratio in train_ratio_list:

    train_len = int(normal_len * train_ratio)
    save_dir = output_dir/f'ratio_{train_ratio}'

    os.makedirs(save_dir, exist_ok=True)

    # train
    train = df_normal[:train_len]
    deeplog_file_generator(
        filename = str(save_dir) + '/train',
        df = train,
        features = ["EventId", "deltaT"],
    )
    print("training size {}".format(train_len))

    # test(normal)
    test_normal = df_normal[train_len:]
    deeplog_file_generator(
        filename = str(save_dir) + '/test_normal',
        df = test_normal,
        features = ["EventId", "deltaT"],
    )
    print("test normal size {}".format(normal_len - train_len))

    # abnormal
    
    # 必要なら EventId のマッピングを復活
    # df_abnormal["EventId"] = df_abnormal["EventId"].progress_apply(
    #     lambda e: event_index_map[e] if event_index_map.get(e) else UNK
    # )

    deeplog_file_generator(
        filename = str(save_dir) + '/test_abnormal',
        df = df_abnormal,
        features = ["EventId", "deltaT"], 
    )
    print("test abnormal size {}".format(len(df_abnormal)))

training size 328
test normal size 492
test abnormal size 0
training size 492
test normal size 328
test abnormal size 0
training size 656
test normal size 164
test abnormal size 0

In [ ]:
# 案２（それぞれファイル名を分ける）

# train
train = df_normal[:train_len]
deeplog_file_generator(
    filename = str(save_dir) + f'/train_{train_ratio}',
    df = train,
    features = ["EventId", "deltaT"],
)
print("training size {}".format(train_len))

# test
test_normal = df_normal[train_len:]
deeplog_file_generator(
    filename = str(save_dir) + f'/test_{(1.0 - train_ratio):.1f}',
    df = test_normal,
    features = ["EventId", "deltaT"],
)

## 1-1 T1105
- interim下にあるsecurity.csvは10日間を抽出したものであることに注意（コードに反映していない）

### 準備

In [9]:
parent_dir = "ScenarioData"
project_name = 'T1105'
ver_number = "2"

### evtx → csv

In [8]:
# test
input_dir = RAW_DIR/parent_dir/project_name
output_dir = INTERIM_DIR/project_name

preprocess.evtx_to_csv_without_eventdata_columns_samplingver(
    evtx_filepath = input_dir/"20240927120753_7EA74D56-6663-313B-2CC1-A7843FCD1AE6/Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = "security2_test",
)

Processing records:   0%|          | 4900/1027696 [00:00<02:01, 8434.40it/s]
Writing to CSV: 100%|██████████| 50/50 [00:00<00:00, 71453.22it/s]

In [9]:
# 実行
preprocess.evtx_to_csv_without_eventdata_columns(
    evtx_filepath = input_dir/"20240927120753_7EA74D56-6663-313B-2CC1-A7843FCD1AE6/Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = "security2",
)

Processing records: 100%|██████████| 1027696/1027696 [1:57:49<00:00, 145.36it/s]
Writing to CSV: 100%|██████████| 1027696/1027696 [00:13<00:00, 74554.24it/s]

### アノテーション

In [10]:
project_name = 'T1105'
ver_number = "2"
ano = pd.read_excel(RAW_DIR/parent_dir/project_name/"取りまとめ後参考"/"AtomicRedTeam_Analyze.xlsx", sheet_name="解析結果")
df = pd.DataFrame()
df["Channel"] = ano["Unnamed: 9"].iloc[1:].values
df["EventRecordID"] = ano["Unnamed: 14"].iloc[1:].values

# labeled = preprocess.anotate_csv(
#     csv_filepath = INTERIM_DIR/project_name/"security2.csv",
#     ano_df = df,
#     output_dir = INTERIM_DIR/project_name,
# )
ano

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/ScenarioData/T1105/取りまとめ後参考/AtomicRedTeam_Analyze.xlsx'

#### 異常期間の同定
- **期間**：9/26 17:57 ~ 9/26 18:55 (73件)

In [15]:
labeled[labeled["Label"] == "anomaly"]

,Level,EventID,EventRecordID,TimeCreated_SystemTime,Channel,Task,Provider_Name,Correlation_RelatedActivityID,Execution_ProcessID,Execution_ThreadID,Security_UserID,Keywords,Content,Correlation_ActivityID,Provider_Guid,Computer,Opcode,Version,Label,date
170778,0,4688,4718654,2024-09-26 17:57:13.401667+00:00,Security,13312,Microsoft-Windows-Security-Auditing,NaN,4,300,NaN,0x8020000000000000,SubjectUserSid=S-1-5-21-143320146-2996204461-2...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},SWAttckd.swtestnet.com,0,2,anomaly,2024-09-26
170779,0,4688,4718655,2024-09-26 17:57:13.409899+00:00,Security,13312,Microsoft-Windows-Security-Auditing,NaN,4,32,NaN,0x8020000000000000,SubjectUserSid=S-1-5-21-143320146-2996204461-2...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},SWAttckd.swtestnet.com,0,2,anomaly,2024-09-26
170780,0,4688,4718656,2024-09-26 17:57:13.442478+00:00,Security,13312,Microsoft-Windows-Security-Auditing,NaN,4,32,NaN,0x8020000000000000,SubjectUserSid=S-1-5-21-143320146-2996204461-2...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},SWAttckd.swtestnet.com,0,2,anomaly,2024-09-26
170834,0,4688,4718710,2024-09-26 17:59:47.880032+00:00,Security,13312,Microsoft-Windows-Security-Auditing,NaN,4,8064,NaN,0x8020000000000000,SubjectUserSid=S-1-5-21-143320146-2996204461-2...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},SWAttckd.swtestnet.com,0,2,anomaly,2024-09-26
170835,0,4688,4718711,2024-09-26 17:59:47.883730+00:00,Security,13312,Microsoft-Windows-Security-Auditing,NaN,4,8744,NaN,0x8020000000000000,SubjectUserSid=S-1-5-21-143320146-2996204461-2...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},SWAttckd.swtestnet.com,0,2,anomaly,2024-09-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171622,0,5156,4719498,2024-09-26 18:48:50.349300+00:00,Security,12810,Microsoft-Windows-Security-Auditing,NaN,4,6840,NaN,0x8020000000000000,ProcessID=1284|Application=\device\harddiskvol...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},SWAttckd.swtestnet.com,0,1,anomaly,2024-09-26
171624,0,5156,4719500,2024-09-26 18:48:50.512531+00:00,Security,12810,Microsoft-Windows-Security-Auditing,NaN,4,6840,NaN,0x8020000000000000,ProcessID=6912|Application=\device\harddiskvol...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},SWAttckd.swtestnet.com,0,1,anomaly,2024-09-26
171627,0,5156,4719503,2024-09-26 18:48:50.929255+00:00,Security,12810,Microsoft-Windows-Security-Auditing,NaN,4,300,NaN,0x8020000000000000,ProcessID=6912|Application=\device\harddiskvol...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},SWAttckd.swtestnet.com,0,1,anomaly,2024-09-26
171912,0,4688,4719788,2024-09-26 18:55:46.865633+00:00,Security,13312,Microsoft-Windows-Security-Auditing,NaN,4,4972,NaN,0x8020000000000000,SubjectUserSid=S-1-5-21-143320146-2996204461-2...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},SWAttckd.swtestnet.com,0,2,anomaly,2024-09-26
171913,0,4688,4719789,2024-09-26 18:55:46.907299+00:00,Security,13312,Microsoft-Windows-Security-Auditing,NaN,4,8308,NaN,0x8020000000000000,SubjectUserSid=S-1-5-21-143320146-2996204461-2...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},SWAttckd.swtestnet.com,0,2,anomaly,2024-09-26

### パース(Drain)
- ここからのsecurity.csvは10日間を抽出したものを想定！！！！！！！！！！！！！！！！

In [41]:
project_name = 'T1105'
ver_number = "2"
input_dir = INTERIM_DIR/project_name
output_dir = INTERIM_DIR/project_name

preprocess.parse_log(input_dir=input_dir, output_dir=output_dir, logfile_name=f'security{ver_number}', parser_type="drain")

Parsing file: ../data/interim/T1105/buffer.csv
Total size after reading CSV: 177827
Parsing done. [Time taken: 0:00:20.552472]

### モデル前データ作成

In [ ]:
ver_number = "2"
input_dir = INTERIM_DIR/project_name
output_dir = PROCESSED_DIR/project_name/f"ver_{ver_number}"
output_dir.mkdir(exist_ok=True)

preprocess.prepare_model_data(
    logdata_filepath = Path(input_dir/"security2_clean_structured.csv"),
    output_dir = output_dir,
)

/home/siwamura/lad2/src/preprocess.py:14: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.

there are 10396 instances (sliding windows) in this dataset

training size 4137
test normal size 6206
test abnormal size 53
training size 6205
test normal size 4138
test abnormal size 53
training size 8274
test normal size 2069
test abnormal size 53
training size 10343

### training

In [ ]:
# train
main.main_cli([
    "train",
    "bert/test3",           # conf/bert_config_name.yaml
    #"default.device_id=0",        # ここに好きな key=value を並べる
    #"default.epochs=10",
])

In [7]:
# テスト
main.main_cli([
    "test",  # run_mode
    "outputs/logbert/bert/T1105/ver_1/ratio_0.8/seq_len_256/r_seed_31/weights/ValTotalbest.pth", # 重みファイルまでの相対パス
    "32",   # eval_batchsize
    "cuda:0",     # gpu
])

==================================================
outputs/logbert/bert/T1105/ver_1/ratio_0.8/seq_len_256/r_seed_31
==================================================
cuda:0 cuda:0
Building Vocab

100%|██████████| 34455/34455 [00:00<00:00, 78005.94it/s]

VOCAB SIZE: 60

Processing normal test data: 100%|██████████| 2069/2069 [00:00<00:00, 3986.61it/s]
Processing abnormal test data: 100%|██████████| 53/53 [00:00<00:00, 3463.34it/s]
100%|██████████| 64/64 [00:01<00:00, 44.75it/s]
100%|██████████| 53/53 [00:00<00:00, 70.81it/s]

Saving test normal results
Saving test abnormal results
[seq_th, FP, TP, TN, FN, Precision, Recall, F1, TPR, FPR]
threshold=0.000['18.0000', '8.0000', '2030.0000', '45.0000', '30.7692', '15.0943', '20.2532', '15.0943', '0.8789']
threshold=0.100['8.0000', '0.0000', '2040.0000', '53.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.3906']
threshold=0.200['0.0000', '0.0000', '2048.0000', '53.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=0.300['0.0000', '0.0000', '2048.0000', '53.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=0.400['0.0000', '0.0000', '2048.0000', '53.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=0.500['0.0000', '0.0000', '2048.0000', '53.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=0.600['0.0000', '0.0000', '2048.0000', '53.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=0.700['0.0000', '0.0000', '2048.0000', '53.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=0.800['0.0000', '0.0000', '2048.0000', '53.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=0.900['0.0000', '0.0000', '2048.0000', '53.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=1.000['0.0000', '0.0000', '2048.0000', '53.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']

## 1-1 T1105 full

### windows & step_size の変換

In [12]:
preprocess.print_equivalent_params_summary(
    preprocess.calculate_equivalent_window_params(
        csv_filepath=NO_MEANING_DIR/"T1105/security2.csv",
        source_mode="fixed",
        source_window_size=100,
        source_step_size=50,
        target_mode="time",
    ),
    source_mode="fixed",
    target_mode="time",
)

============================================================
Sliding Window パラメータ変換結果
============================================================
入力CSV: ../data/no_meaning/T1105/security2.csv
変換方向: fixed → time
------------------------------------------------------------
【データ統計】
  総イベント数:    1,027,696
  総時間:          3855245.00 秒
  平均イベント率:  0.2666 events/sec
  平均イベント間隔: 3.7513 sec/event
------------------------------------------------------------
【変換結果】
  推奨 window_size: 375.1347674798773
  推奨 step_size:   187.56738373993866
  元の平均シーケンス長: 100.00
============================================================

/home/siwamura/My_lad/src/preprocess.py:64: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  event_data_element = root.find(

### モデル前データ作成

In [ ]:
parent_dir = "ScenarioData"
project_name = 'T1105(full)_time'
ver_number = "2"

input_dir = NO_MEANING_DIR/"T1105"
output_dir = PROCESSED_DIR/project_name/f"ver_{ver_number}"
output_dir.mkdir(exist_ok=True, parents=True)

preprocess.prepare_model_data(
    logdata_filepath = Path(input_dir/"security2_structured.csv"),
    output_dir = output_dir,
    mode="time",
    window_size=375,
    step_size=187,
)

/home/siwamura/My_lad/src/preprocess.py:640: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  data["timestamp"] = data["datetime"].view("int64") // 10**9

there are 20552 instances (sliding windows) in this dataset

training size 12319
test normal size 8213
test abnormal size 20
training size 16425
test normal size 4107
test abnormal size 20
training size 20532

### train & test

In [ ]:
# train
main.main_cli([
    "train",
    "bert/T1105(full)_time",           # conf/bert_config_name.yaml
    #"default.device_id=0",        # ここに好きな key=value を並べる
    #"default.epochs=10",
])

setup
Building Vocab

100%|██████████| 20532/20532 [00:00<00:00, 31944.31it/s]

VOCAB SIZE: 60
before filtering short session
train size  14783
valid size  1642
========================================

100%|██████████| 16425/16425 [00:05<00:00, 3270.09it/s]
/home/siwamura/My_lad/.venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 10, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(

========================================
Num of train seqs 14783
Num of valid seqs 1642
========================================

14it [00:13,  1.02it/s]

KeyboardInterrupt:

In [ ]:
# テスト
main.main_cli([
    "test",  # run_mode
    "outputs/logbert/bert/T1105/ver_1/ratio_0.8/seq_len_256/r_seed_31/weights/ValTotalbest.pth", # 重みファイルまでの相対パス
    "32",   # eval_batchsize
    "cuda:0",     # gpu
])

## 1-2 VSCode1

### 準備

In [4]:
parent_dir = "ScenarioData"
project_name = 'VSCode1'

### evtx → csv

In [10]:
# test
input_dir = RAW_DIR/parent_dir/project_name
output_dir = INTERIM_DIR/project_name

preprocess.evtx_to_csv_without_eventdata_columns_samplingver(
    evtx_filepath = input_dir/"20240706063537_7EA74D56-6663-313B-2CC1-A7843FCD1AE6/Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = "security2_test",
)

Processing records:   5%|▌         | 4900/93912 [00:00<00:10, 8582.05it/s]
Writing to CSV: 100%|██████████| 50/50 [00:00<00:00, 68556.78it/s]

In [11]:
# 実行
preprocess.evtx_to_csv_without_eventdata_columns(
    evtx_filepath = input_dir/"20240706063537_7EA74D56-6663-313B-2CC1-A7843FCD1AE6/Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = "security2",
)

Processing records: 100%|██████████| 93912/93912 [09:13<00:00, 169.80it/s]
Writing to CSV: 100%|██████████| 93912/93912 [00:01<00:00, 67158.05it/s]

### パース(Drain)

In [5]:
project_name = 'VSCode1'
ver_number = "2"
input_dir = INTERIM_DIR/project_name
output_dir = INTERIM_DIR/project_name

preprocess.parse_log(input_dir=input_dir, output_dir=output_dir, logfile_name=f'security{ver_number}', parser_type="drain")

Parsing file: ../data/interim/VSCode1/buffer.csv
Total size after reading CSV: 72694
Parsing done. [Time taken: 0:00:08.328695]

### windows & step_size の変換

In [13]:
preprocess.print_equivalent_params_summary(
    preprocess.calculate_equivalent_window_params(
        csv_filepath=INTERIM_DIR/"VSCode1/security2.csv",
        source_mode="fixed",
        source_window_size=100,
        source_step_size=50,
        target_mode="time",
    ),
    source_mode="fixed",
    target_mode="time",
)

============================================================
Sliding Window パラメータ変換結果
============================================================
入力CSV: ../data/interim/VSCode1/security2.csv
変換方向: fixed → time
------------------------------------------------------------
【データ統計】
  総イベント数:    72,698
  総時間:          825773.00 秒
  平均イベント率:  0.0880 events/sec
  平均イベント間隔: 11.3590 sec/event
------------------------------------------------------------
【変換結果】
  推奨 window_size: 1135.8950727667886
  推奨 step_size:   567.9475363833943
  元の平均シーケンス長: 100.00
============================================================

/home/siwamura/My_lad/src/preprocess.py:1107: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  data["timestamp"] = data["datetime"].view("int64") // 10**9

## 1-3 WEB01

### 準備

In [20]:
parent_dir = "ScenarioData"
project_name = 'WEB1'
ver_number = "2"

### evtx → csv

In [13]:
# test
input_dir = RAW_DIR/parent_dir/project_name
output_dir = INTERIM_DIR/project_name

preprocess.evtx_to_csv_without_eventdata_columns_samplingver(
    evtx_filepath = input_dir/"20240317044842_7EA74D56-6663-313B-2CC1-A7843FCD1AE6/Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = "security2_test",
)

Processing records:   2%|▏         | 4900/215806 [00:00<00:27, 7632.09it/s]
Writing to CSV: 100%|██████████| 50/50 [00:00<00:00, 61230.72it/s]

In [14]:
# 実行
preprocess.evtx_to_csv_without_eventdata_columns(
    evtx_filepath = input_dir/"20240317044842_7EA74D56-6663-313B-2CC1-A7843FCD1AE6/Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = "security2",
)

Processing records: 100%|██████████| 215806/215806 [21:56<00:00, 163.89it/s]
Writing to CSV: 100%|██████████| 215806/215806 [00:02<00:00, 72085.06it/s]

### 余計な区間を削除（11/22~11/23）

In [15]:
project_name = 'WEB3'
ver_number = "2"
data = pd.read_csv(INTERIM_DIR/project_name/f"security{ver_number}.csv")
data["TimeCreated_SystemTime"] = pd.to_datetime(
    data["TimeCreated_SystemTime"], 
    errors="coerce",      # 変換できないものは NaT にする
)

data["date"] = data["TimeCreated_SystemTime"].dt.date

filtered = data[
    (data["date"] <= pd.to_datetime("2024-11-01").date()) &
    (data["date"] >= pd.to_datetime("2023-12-01").date())
]

# データ上書き注意！！！！！！！！！！！！！！
filtered.to_csv(INTERIM_DIR/project_name/f"security{ver_number}.csv", index=False)

### アノテーション

In [ ]:
project_name = 'WEB1'
ver_number = "2"
ano = pd.read_excel(RAW_DIR/parent_dir/"_anotation"/project_name/"web1_labeled_incident_data.xlsx")
df = pd.DataFrame()
df["Channel"] = ano["Channel"].values
df["EventRecordID"] = ano["RecordID"].values

labeled = preprocess.anotate_csv(
    csv_filepath = INTERIM_DIR/project_name/"security2.csv",
    ano_df = df,
    output_dir = INTERIM_DIR/project_name,
)

#### 異常期間の同定
- **期間**：3/14 15:00 ~ 3/17 16:48 (21162件)

In [ ]:
labeled[labeled["Label"] == "anomaly"]

###

### パース(Drain)

In [24]:
input_dir = INTERIM_DIR/project_name
output_dir = INTERIM_DIR/project_name
preprocess.parse_log(input_dir=input_dir, output_dir=output_dir, logfile_name='security2', parser_type="drain")

Parsing file: ../data/interim/WEB1/buffer.csv
Total size after reading CSV: 194072
Parsing done. [Time taken: 0:00:22.991458]

### windows & step_size の変換

In [11]:
preprocess.print_equivalent_params_summary(
    preprocess.calculate_equivalent_window_params(
        csv_filepath=INTERIM_DIR/"WEB1/security2.csv",
        source_mode="fixed",
        source_window_size=100,
        source_step_size=50,
        target_mode="time",
    ),
    source_mode="fixed",
    target_mode="time",
)

============================================================
Sliding Window パラメータ変換結果
============================================================
入力CSV: ../data/interim/WEB1/security2.csv
変換方向: fixed → time
------------------------------------------------------------
【データ統計】
  総イベント数:    194,074
  総時間:          990014.00 秒
  平均イベント率:  0.1960 events/sec
  平均イベント間隔: 5.1012 sec/event
------------------------------------------------------------
【変換結果】
  推奨 window_size: 510.12191226027187
  推奨 step_size:   255.06095613013593
  元の平均シーケンス長: 100.00
============================================================

/home/siwamura/My_lad/src/preprocess.py:1107: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  data["timestamp"] = data["datetime"].view("int64") // 10**9

## 1-4 WEB02

### 準備

In [28]:
parent_dir = "ScenarioData"
project_name = 'WEB2'
ver_number = "2"

### evtx → csv

In [ ]:
# test
input_dir = RAW_DIR/parent_dir/project_name
output_dir = INTERIM_DIR/project_name

preprocess.evtx_to_csv_without_eventdata_columns_samplingver(
    evtx_filepath = input_dir/"20240317051629_7EA74D56-6663-313B-2CC1-A7843FCD1AE6/Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = f"security{ver_number}_test",
)

Processing records:   2%|▏         | 4900/215808 [00:00<00:33, 6286.26it/s]
Writing to CSV: 100%|██████████| 50/50 [00:00<00:00, 46386.91it/s]

In [32]:
# 実行
preprocess.evtx_to_csv_without_eventdata_columns(
    evtx_filepath = input_dir/"20240317051629_7EA74D56-6663-313B-2CC1-A7843FCD1AE6/Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = f"security{ver_number}",
)

Processing records: 100%|██████████| 215808/215808 [26:05<00:00, 137.89it/s]
Writing to CSV: 100%|██████████| 215808/215808 [00:03<00:00, 64105.31it/s]

### アノテーション

In [29]:
project_name = 'WEB2'
ver_number = "2"
ano = pd.read_excel(RAW_DIR/parent_dir/"_anotation"/project_name/"web2_labeled_incident_data.xlsx")
df = pd.DataFrame()
df["Channel"] = ano["Channel"].values
df["EventRecordID"] = ano["RecordID"].values

labeled = preprocess.anotate_csv(
    csv_filepath = INTERIM_DIR/project_name/"security2.csv",
    ano_df = df,
    output_dir = INTERIM_DIR/project_name,
)

#### 異常期間の同定
- **期間**：3/14 15:00 ~ 3/17 17:17 (21683件)

In [ ]:
labeled[labeled["Label"] == "anomaly"]

### パース(Drain)

In [30]:
project_name = 'WEB2'
ver_number = "2"
input_dir = INTERIM_DIR/project_name
output_dir = INTERIM_DIR/project_name
preprocess.parse_log(input_dir=input_dir, output_dir=output_dir, logfile_name='security2', parser_type="drain")

Parsing file: ../data/interim/WEB2/buffer.csv
Total size after reading CSV: 215806
Parsing done. [Time taken: 0:00:25.667182]

In [12]:
preprocess.print_equivalent_params_summary(
    preprocess.calculate_equivalent_window_params(
        csv_filepath=INTERIM_DIR/"WEB2/security2.csv",
        source_mode="fixed",
        source_window_size=100,
        source_step_size=50,
        target_mode="time",
    ),
    source_mode="fixed",
    target_mode="time",
)

============================================================
Sliding Window パラメータ変換結果
============================================================
入力CSV: ../data/interim/WEB2/security2.csv
変換方向: fixed → time
------------------------------------------------------------
【データ統計】
  総イベント数:    195,234
  総時間:          991677.00 秒
  平均イベント率:  0.1969 events/sec
  平均イベント間隔: 5.0794 sec/event
------------------------------------------------------------
【変換結果】
  推奨 window_size: 507.9427763606748
  推奨 step_size:   253.9713881803374
  元の平均シーケンス長: 100.00
============================================================

/home/siwamura/My_lad/src/preprocess.py:1107: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  data["timestamp"] = data["datetime"].view("int64") // 10**9

## 1-5 WEB03

### 準備

In [33]:
parent_dir = "ScenarioData"
project_name = 'WEB3'
ver_number = "2"

### evtx → csv

In [34]:
# test
input_dir = RAW_DIR/parent_dir/project_name
output_dir = INTERIM_DIR/project_name

preprocess.evtx_to_csv_without_eventdata_columns_samplingver(
    evtx_filepath = input_dir/"20240317054607_7EA74D56-6663-313B-2CC1-A7843FCD1AE6/Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = f"security{ver_number}_test",
)

Processing records:   2%|▏         | 4900/215773 [00:00<00:36, 5798.09it/s]
Writing to CSV: 100%|██████████| 50/50 [00:00<00:00, 46172.44it/s]

In [35]:
# 実行
preprocess.evtx_to_csv_without_eventdata_columns(
    evtx_filepath = input_dir/"20240317054607_7EA74D56-6663-313B-2CC1-A7843FCD1AE6/Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = f"security{ver_number}",
)

Processing records: 100%|██████████| 215773/215773 [26:04<00:00, 137.94it/s]
Writing to CSV: 100%|██████████| 215773/215773 [00:03<00:00, 62537.91it/s]

### アノテーション

### パース(Drain)

In [17]:
input_dir = INTERIM_DIR/project_name
output_dir = INTERIM_DIR/project_name

df = pd.read_csv(input_dir/"security.csv")
df = df.dropna(subset=["Content"]) # Contentカラムに欠損値をもつ行を削除
df.to_csv(input_dir / "security_clean.csv", index=False)

In [ ]:
preprocess.parse_log(input_dir=input_dir, output_dir=output_dir, logfile_name='security_clean', parser_type="drain")

### windows & step_size 変換

In [17]:
preprocess.print_equivalent_params_summary(
    preprocess.calculate_equivalent_window_params(
        csv_filepath=INTERIM_DIR/"WEB3/security2.csv",
        source_mode="fixed",
        source_window_size=100,
        source_step_size=50,
        target_mode="time",
    ),
    source_mode="fixed",
    target_mode="time",
)

============================================================
Sliding Window パラメータ変換結果
============================================================
入力CSV: ../data/interim/WEB3/security2.csv
変換方向: fixed → time
------------------------------------------------------------
【データ統計】
  総イベント数:    193,598
  総時間:          993458.00 秒
  平均イベント率:  0.1949 events/sec
  平均イベント間隔: 5.1316 sec/event
------------------------------------------------------------
【変換結果】
  推奨 window_size: 513.1550945774233
  推奨 step_size:   256.5775472887116
  元の平均シーケンス長: 100.00
============================================================

/home/siwamura/My_lad/src/preprocess.py:1107: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  data["timestamp"] = data["datetime"].view("int64") // 10**9

## 1-6 総合データ（Integrated）

### csv ⇒ 統合csv

In [15]:
input_dir = output_dir = INTERIM_DIR/"Integrated"

project_list = ["T1105", "WEB1", "WEB2"]

# T1105 だけフルデータが別ディレクトリ下なので、別扱い
df = pd.read_csv(NO_MEANING_DIR/"T1105/security2_complement.csv")
df["project"] = "T1105_C"

for project in project_list:
    dir = Path(INTERIM_DIR / project / "security2.csv")
    temp_df = pd.read_csv(dir)
    temp_df["project"] = str(project)    
    df = pd.concat([df, temp_df], ignore_index=True)

df.to_csv(output_dir/"security_integrated.csv", index=False)

### パース(Drain)

In [16]:
input_dir = output_dir = INTERIM_DIR/"Integrated"
preprocess.parse_log(input_dir=input_dir, output_dir=output_dir, logfile_name='security_integrated', parser_type="drain", integrated=True)

Parsing file: ../data/interim/Integrated/buffer.csv
Total size after reading CSV: 1416987
Parsing done. [Time taken: 0:03:10.633761]

### windows & step_size の変換

- 各シナリオの算術平均で調整

In [18]:
375*0.6 + 1135*0.04 + 510*0.12 + 507*0.12 + 513*0.12

453.99999999999994

### モデル前データ作成

In [7]:
preprocess.prepare_integrated_model_data(
    logdata_filepath = INTERIM_DIR/"Integrated"/"security_integrated_structured.csv", 
    output_dir = PROCESSED_DIR/"Integrated_fixed",
    window_size=100,
    step_size=50,
    mode="fixed",
)

/home/siwamura/My_lad/src/preprocess.py:850: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  data["timestamp"] = data["datetime"].view("int64") // 10**9

there are 16996 instances (sliding windows) in this dataset

there are 3555 instances (sliding windows) in this dataset

there are 3880 instances (sliding windows) in this dataset

there are 3903 instances (sliding windows) in this dataset

there are 16996 instances (sliding windows) in this dataset

there are 3555 instances (sliding windows) in this dataset

there are 3880 instances (sliding windows) in this dataset

there are 3903 instances (sliding windows) in this dataset

vocab size 9436
======================================================================
Sequence Length Statistics Report
======================================================================
Generated: 2025-12-19 09:46:04
Mode: fixed
Window Size: 100
Step Size: 50
======================================================================

[Ratio: 0.8]
--------------------------------------------------
  train:
    Count:    24,544
    Avg Len:  100.00
    Min Len:  100
    Max Len:  100
    Std Dev:  0.00
  test_normal:
    Count:    1,888
    Avg Len:  100.00
    Min Len:  100
    Max Len:  100
    Std Dev:  0.00
  test_abnormal:
    Count:    1,902
    Avg Len:  100.00
    Min Len:  100
    Max Len:  100
    Std Dev:  0.00

======================================================================

Statistics saved to: ../data/processed/Integrated_fixed/seq_stats.txt

### 実行

In [ ]:
# train
main.main_cli([
    "train",
    "bert/test",           # conf/bert_config_name.yaml
    #"default.device_id=0",        # ここに好きな key=value を並べる
    #"default.epochs=10",
])

In [ ]:
"""
HyperSphereLossなしでテスト
Jupyter Notebookで実行してください
"""

import sys
sys.path.insert(0, '/home/siwamura/My_lad/src')

from main import main_cli

print("=" * 80)
print("🚀 HyperSphereLoss無効化テスト")
print("=" * 80)
print("HyperSphereLossを無効化してトレーニングします")
print("これでNaNが消えれば、HyperSphereLossが原因です")
print("=" * 80)

try:
    main_cli([
        "train",
        "bert/test",
        "dataset.sample.seq_len=128",
        "default.epochs=2",
        "loss.hypersphere.bias=0.0",  # HyperSphereLossを無効化
        "loss.mask.bias=1.0",  # MaskLossのみ使用
    ])
    
    print("\n" + "=" * 80)
    print("✅ トレーニング完了（HyperSphereLossなし）")
    print("=" * 80)
    print("\n結論:")
    print("  HyperSphereLossを無効化すれば正常に動作する")
    print("  → HyperSphereLossの実装に問題がある")

except Exception as e:
    print(f"\n❌ Error: {e}")
    import traceback
    traceback.print_exc()

## 1-7 自分のパソコン

In [9]:
project_name = 'My_logs/soraz'
number = "01"
ver_number = "2"

In [10]:
# test
input_dir = RAW_DIR/project_name
output_dir = INTERIM_DIR/project_name/number

preprocess.evtx_to_csv_without_eventdata_columns_samplingver(
    evtx_filepath = input_dir/"LAPTOP-ULHFC97T_20251211151542/Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = f"security{ver_number}_test",
)

Processing records:   1%|▏         | 4900/388005 [00:00<01:12, 5256.93it/s]
Writing to CSV: 100%|██████████| 50/50 [00:00<00:00, 28320.76it/s]

In [11]:
# 実行
preprocess.evtx_to_csv_without_eventdata_columns(
    evtx_filepath = input_dir/"LAPTOP-ULHFC97T_20251211151542/Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = f"security{ver_number}",
)

Processing records: 100%|██████████| 388005/388005 [48:06<00:00, 134.43it/s]
Writing to CSV: 100%|██████████| 388005/388005 [00:11<00:00, 34767.03it/s]

In [5]:
# パース
input_dir = output_dir = INTERIM_DIR/"My_logs/soraz/01"
preprocess.parse_log(input_dir=input_dir, output_dir=output_dir, logfile_name='security2', parser_type="drain", integrated=True)

Parsing file: ../data/interim/My_logs/soraz/01/buffer.csv
Total size after reading CSV: 387998
Parsing done. [Time taken: 0:00:40.911555]

In [5]:
# アノテーション（とりあえず全部0を仮定）
df = pd.read_csv(INTERIM_DIR/"My_logs/soraz/security2.csv")
df["Label"] = "-"
df.to_csv(INTERIM_DIR/"My_logs/soraz/security2.csv")

## 1-8 総合データ２（＋自分のパソコン ver）

In [10]:
output_dir = INTERIM_DIR/"Integrated2"
output_dir.mkdir(exist_ok=True)

project_list = ["T1105", "WEB1", "WEB2"] # 正常onlyデータには"_C"

# T1105 だけフルデータが別ディレクトリ下なので、別扱い
df = pd.read_csv(NO_MEANING_DIR/"T1105/security2_complement.csv")
df["project"] = "T1105_C"

tmp = pd.read_csv(INTERIM_DIR/"My_logs/soraz/security2.csv")
tmp["project"] = "soraz_C"
df = pd.concat([df, tmp], ignore_index=True)

for project in project_list:
    dir = Path(INTERIM_DIR / project / "security2.csv")
    temp_df = pd.read_csv(dir)
    temp_df["project"] = str(project)    
    df = pd.concat([df, temp_df], ignore_index=True)

df.to_csv(output_dir/"security_integrated.csv", index=False)

In [11]:
input_dir = output_dir = INTERIM_DIR/"Integrated2"
preprocess.parse_log(input_dir=input_dir, output_dir=output_dir, logfile_name='security_integrated', parser_type="drain", integrated=True)

/home/siwamura/My_lad/src/preprocess.py:374: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  tmp = pd.read_csv(input_dir / f"{logfile_name}.csv")

Parsing file: ../data/interim/Integrated2/buffer.csv

/home/siwamura/My_lad/src/preprocess.py:319: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  logdf = pd.read_csv(log_file, encoding="utf-8")

Total size after reading CSV: 1804985
Parsing done. [Time taken: 0:03:19.525843]

In [6]:
preprocess.prepare_integrated_model_data(
    logdata_filepath = INTERIM_DIR/"Integrated2"/"security_integrated_structured.csv", 
    output_dir = PROCESSED_DIR/"Integrated2_fixed",
    window_size=200,
    step_size=100,
    mode="fixed",
)

/home/siwamura/My_lad/src/preprocess.py:843: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(logdata_filepath)
/home/siwamura/My_lad/src/preprocess.py:850: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  data["timestamp"] = data["datetime"].view("int64") // 10**9

there are 8497 instances (sliding windows) in this dataset

there are 3878 instances (sliding windows) in this dataset

there are 1777 instances (sliding windows) in this dataset

there are 1939 instances (sliding windows) in this dataset

there are 1951 instances (sliding windows) in this dataset

there are 8497 instances (sliding windows) in this dataset

there are 3878 instances (sliding windows) in this dataset

there are 1777 instances (sliding windows) in this dataset

there are 1939 instances (sliding windows) in this dataset

there are 1951 instances (sliding windows) in this dataset

vocab size 4688
======================================================================
Sequence Length Statistics Report
======================================================================
Generated: 2025-12-15 18:33:16
Mode: fixed
Window Size: 200
Step Size: 100
======================================================================

[Ratio: 0.8]
--------------------------------------------------
  train:
    Count:    16,124
    Avg Len:  200.00
    Min Len:  200
    Max Len:  200
    Std Dev:  0.00
  test_normal:
    Count:    939
    Avg Len:  200.00
    Min Len:  200
    Max Len:  200
    Std Dev:  0.00
  test_abnormal:
    Count:    979
    Avg Len:  200.00
    Min Len:  200
    Max Len:  200
    Std Dev:  0.00

======================================================================

Statistics saved to: ../data/processed/Integrated2_fixed/seq_stats.txt

## T1007

In [4]:
parent_dir = "ScenarioData"
project_name = 'T1007'
ver_number = "2"

### evtx → csv

In [5]:
# test
input_dir = RAW_DIR/parent_dir/project_name
output_dir = INTERIM_DIR/project_name

preprocess.evtx_to_csv_without_eventdata_columns_samplingver(
    evtx_filepath = input_dir/"Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = "security2_test",
)

Processing records:   3%|▎         | 4900/157110 [00:00<00:22, 6729.56it/s]
Writing to CSV: 100%|██████████| 50/50 [00:00<00:00, 55686.46it/s]

In [8]:
# 実行
preprocess.evtx_to_csv_without_eventdata_columns(
    evtx_filepath = input_dir/"Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = "security2",
)

Processing records: 100%|██████████| 157110/157110 [16:15<00:00, 161.14it/s]
Writing to CSV: 100%|██████████| 157110/157110 [00:02<00:00, 53895.43it/s]

### アノテーション

In [ ]:
project_name = 'T1105'
ver_number = "2"
ano = pd.read_excel(RAW_DIR/parent_dir/project_name/"取りまとめ後参考"/"AtomicRedTeam_Analyze.xlsx", sheet_name="解析結果")
df = pd.DataFrame()
df["Channel"] = ano["Unnamed: 9"].iloc[1:].values
df["EventRecordID"] = ano["Unnamed: 14"].iloc[1:].values

# labeled = preprocess.anotate_csv(
#     csv_filepath = INTERIM_DIR/project_name/"security2.csv",
#     ano_df = df,
#     output_dir = INTERIM_DIR/project_name,
# )

## T1055

In [ ]:
parent_dir = "ScenarioData"
project_name = 'T1055'

### evtx → csv

In [10]:
# test
input_dir = RAW_DIR/parent_dir/project_name
output_dir = INTERIM_DIR/project_name

preprocess.evtx_to_csv_without_eventdata_columns_samplingver(
    evtx_filepath = input_dir/"Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = "security2_test",
)

Processing records:   0%|          | 4900/1448467 [00:00<03:24, 7074.79it/s]
Writing to CSV: 100%|██████████| 50/50 [00:00<00:00, 52904.94it/s]

In [12]:
# 実行
preprocess.evtx_to_csv_without_eventdata_columns(
    evtx_filepath = input_dir/"Evtx/Security.evtx",
    output_dir = output_dir,
    output_filename = "security2",
)

Processing records: 100%|██████████| 1448467/1448467 [2:55:19<00:00, 137.70it/s]
Writing to CSV: 100%|██████████| 1448467/1448467 [00:26<00:00, 53687.98it/s]

### アノテーション

In [22]:
parent_dir = "ScenarioData"
project_name = 'T1055'

ano = pd.read_excel(RAW_DIR/parent_dir/"_anotation/T1055/T1055_20250304.xlsx")
df = pd.DataFrame()
df["Channel"] = ano["Unnamed: 9"].iloc[1:].values
df["EventRecordID"] = ano["Unnamed: 14"].iloc[1:].values

df = df[df["Channel"] == "Sec"]

df["EventRecordID"] = df["EventRecordID"].astype(int)

labeled = preprocess.anotate_csv(
    csv_filepath = INTERIM_DIR/project_name/"security2.csv",
    ano_df = df,
    output_dir = INTERIM_DIR/project_name,
)

### パース

In [27]:
project_name = 'T1055'
input_dir = INTERIM_DIR/project_name
output_dir = INTERIM_DIR/project_name
preprocess.parse_log(input_dir=input_dir, output_dir=output_dir, logfile_name='security2', parser_type="drain")

Parsing file: ../data/interim/T1055/buffer.csv
Total size after reading CSV: 1448457
Parsing done. [Time taken: 0:02:27.262745]

## 補足

### "Channel="を削ぐ
- 一応過程として残す

In [14]:
def remove_leading_channel_security(s):
    # NaN はそのまま返す
    if pd.isna(s):
        return s

    text = str(s)
    parts = text.split(";")

    # 先頭がちょうど "Channel=Security" なら、それを落とす
    if parts and parts[0] == "Channel=Security":
        parts = parts[1:]

    # 空文字を除いて再結合
    parts = [p for p in parts if p != ""]
    return ";".join(parts)

In [30]:
project_name = "WEB1"
input_dir = INTERIM_DIR/project_name

df = pd.read_csv(input_dir/"security.csv")
# Content カラムに適用
df["Content"] = df["Content"].apply(remove_leading_channel_security)
# ""をNaNに変換
df.loc[df["Content"] == "", "Content"] = np.nan

In [31]:
# 保存
df.to_csv(input_dir/"security_.csv", index=False)

### 余計なデータを消す
scenario：削除対象 [正常期間]
- VSCode1：(2024)5/22 [(2024)6/27~7/6]
- WEB1：(2023)11/22 ~ 11/23 [(2024)3/6~3/17]
- WEB2：(2023)11/22 ~ 11/23 [(2024)3/6~3/17]

In [11]:
preprocess.delete_unwanted_logs(
    input_filepath=Path(INTERIM_DIR /"VSCode1"/ "security2.csv"),
    start_date="2024-06-01",
    end_date="2024-07-30",
)

,TimeCreated_SystemTime,Security_UserID,Correlation_ActivityID,Channel,Version,Content,Correlation_RelatedActivityID,Provider_Guid,Keywords,Opcode,EventID,Provider_Name,Computer,Task,EventRecordID,Level,Execution_ProcessID,Execution_ThreadID,date
7458,2024-06-27 05:12:47.146389+00:00,NaN,NaN,Security,1,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4616,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,12288,2543604,0,4,6596,2024-06-27
7459,2024-06-27 05:12:48.635813+00:00,NaN,NaN,Security,2,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4688,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,13312,2543605,0,4,6596,2024-06-27
7460,2024-06-27 05:12:50.183855+00:00,NaN,NaN,Security,2,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4688,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,13312,2543606,0,4,2332,2024-06-27
7461,2024-06-27 05:12:50.618172+00:00,NaN,NaN,Security,2,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4688,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,13312,2543607,0,4,2648,2024-06-27
7462,2024-06-27 05:12:50.619019+00:00,NaN,NaN,Security,2,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4688,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,13312,2543608,0,4,2988,2024-06-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93907,2024-07-06 18:35:40.437977+00:00,NaN,NaN,Security,0,ProcessId=676|Application=\device\harddiskvolu...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,5158,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,12810,2630053,0,4,5552,2024-07-06
93908,2024-07-06 18:35:40.438011+00:00,NaN,NaN,Security,1,ProcessID=676|Application=\device\harddiskvolu...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,5156,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,12810,2630054,0,4,5552,2024-07-06
93909,2024-07-06 18:35:40.498657+00:00,NaN,NaN,Security,2,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4688,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,13312,2630055,0,4,6436,2024-07-06
93910,2024-07-06 18:35:40.527555+00:00,NaN,NaN,Security,2,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4688,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,13312,2630056,0,4,6436,2024-07-06
93911,2024-07-06 18:35:40.682627+00:00,NaN,NaN,Security,0,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4673,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,13056,2630057,0,4,6436,2024-07-06

In [12]:
preprocess.delete_unwanted_logs(
    input_filepath=Path(INTERIM_DIR /"WEB1"/ "security2.csv"),
    start_date="2024-03-01",
    end_date="2024-03-30",
)

,TimeCreated_SystemTime,Security_UserID,Correlation_ActivityID,Channel,Version,Content,Correlation_RelatedActivityID,Provider_Guid,Keywords,Opcode,EventID,Provider_Name,Computer,Task,EventRecordID,Level,Execution_ProcessID,Execution_ThreadID,date,Label
0,2024-03-06 05:48:33.170567+00:00,NaN,{326660a5-67c0-0001-6861-6632c067da01},Security,1,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4702,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,12804,1367106,0,692,6000,2024-03-06,-
1,2024-03-06 05:48:33.174620+00:00,NaN,{326660a5-67c0-0001-6861-6632c067da01},Security,1,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4702,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,12804,1367107,0,692,6000,2024-03-06,-
2,2024-03-06 05:48:33.180763+00:00,NaN,{326660a5-67c0-0001-6861-6632c067da01},Security,1,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4702,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,12804,1367108,0,692,6000,2024-03-06,-
3,2024-03-06 05:48:33.184887+00:00,NaN,{326660a5-67c0-0001-6861-6632c067da01},Security,1,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4702,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,12804,1367109,0,692,6000,2024-03-06,-
4,2024-03-06 05:48:38.115097+00:00,NaN,NaN,Security,0,ProcessId=8596|Application=\device\harddiskvol...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,5158,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,12810,1367110,0,4,5136,2024-03-06,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194069,2024-03-17 16:48:46.498323+00:00,NaN,{81f03b91-7558-0001-6c3c-f0815875da01},Security,0,TargetUserName=WDAGUtilityAccount|TargetDomain...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4798,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,13824,1561175,0,680,8556,2024-03-17,-
194070,2024-03-17 16:48:46.498625+00:00,NaN,{81f03b91-7558-0001-6c3c-f0815875da01},Security,0,TargetUserName=一般|TargetDomainName=SWATTCKD|Ta...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4798,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,13824,1561176,0,680,8556,2024-03-17,-
194071,2024-03-17 16:48:46.617451+00:00,NaN,NaN,Security,2,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4688,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,13312,1561177,0,4,5188,2024-03-17,anomaly
194072,2024-03-17 16:48:46.646482+00:00,NaN,NaN,Security,2,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4688,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,13312,1561178,0,4,2656,2024-03-17,anomaly
194073,2024-03-17 16:48:47.110657+00:00,NaN,NaN,Security,0,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,NaN,{54849625-5478-4994-a5ba-3e3b0328c30d},0x8020000000000000,0,4673,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,13056,1561179,0,4,7440,2024-03-17,-

In [14]:
preprocess.delete_unwanted_logs(
    input_filepath=Path(INTERIM_DIR /"WEB2"/ "security2.csv"),
    start_date="2024-03-01",
    end_date="2024-03-30",
)

,Security_UserID,Level,Keywords,Channel,Content,EventID,Correlation_ActivityID,TimeCreated_SystemTime,Correlation_RelatedActivityID,Task,Execution_ProcessID,Execution_ThreadID,Provider_Name,Computer,Version,Opcode,EventRecordID,Provider_Guid,Label,date
0,NaN,0,0x8020000000000000,Security,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,4702,{326660a5-67c0-0001-6861-6632c067da01},2024-03-06 05:48:33.170567+00:00,NaN,12804,692,6000,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,1,0,1367106,{54849625-5478-4994-a5ba-3e3b0328c30d},-,2024-03-06
1,NaN,0,0x8020000000000000,Security,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,4702,{326660a5-67c0-0001-6861-6632c067da01},2024-03-06 05:48:33.174620+00:00,NaN,12804,692,6000,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,1,0,1367107,{54849625-5478-4994-a5ba-3e3b0328c30d},-,2024-03-06
2,NaN,0,0x8020000000000000,Security,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,4702,{326660a5-67c0-0001-6861-6632c067da01},2024-03-06 05:48:33.180763+00:00,NaN,12804,692,6000,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,1,0,1367108,{54849625-5478-4994-a5ba-3e3b0328c30d},-,2024-03-06
3,NaN,0,0x8020000000000000,Security,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,4702,{326660a5-67c0-0001-6861-6632c067da01},2024-03-06 05:48:33.184887+00:00,NaN,12804,692,6000,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,1,0,1367109,{54849625-5478-4994-a5ba-3e3b0328c30d},-,2024-03-06
4,NaN,0,0x8020000000000000,Security,ProcessId=8596|Application=\device\harddiskvol...,5158,NaN,2024-03-06 05:48:38.115097+00:00,NaN,12810,4,5136,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,0,0,1367110,{54849625-5478-4994-a5ba-3e3b0328c30d},-,2024-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195229,NaN,0,0x8020000000000000,Security,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,4688,NaN,2024-03-17 17:16:28.766081+00:00,NaN,13312,4,3960,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,2,0,1562335,{54849625-5478-4994-a5ba-3e3b0328c30d},anomaly,2024-03-17
195230,NaN,0,0x8020000000000000,Security,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,4688,NaN,2024-03-17 17:16:29.024967+00:00,NaN,13312,4,8988,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,2,0,1562336,{54849625-5478-4994-a5ba-3e3b0328c30d},anomaly,2024-03-17
195231,NaN,0,0x8020000000000000,Security,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,4688,NaN,2024-03-17 17:16:29.153864+00:00,NaN,13312,4,3960,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,2,0,1562337,{54849625-5478-4994-a5ba-3e3b0328c30d},anomaly,2024-03-17
195232,NaN,0,0x8020000000000000,Security,SubjectUserSid=S-1-5-18|SubjectUserName=SWATTC...,4673,NaN,2024-03-17 17:16:29.450386+00:00,NaN,13056,4,8988,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,0,0,1562338,{54849625-5478-4994-a5ba-3e3b0328c30d},-,2024-03-17
195233,NaN,0,0x8020000000000000,Security,ProcessId=8200|Application=\device\harddiskvol...,5158,NaN,2024-03-17 17:16:30.306303+00:00,NaN,12810,4,3960,Microsoft-Windows-Security-Auditing,SWAttckd.swtestnet.com,0,0,1562339,{54849625-5478-4994-a5ba-3e3b0328c30d},-,2024-03-17

### T1105のフルバージョンのstructuredを作成

In [8]:
preprocess.parse_log(
    input_dir=NO_MEANING_DIR/"T1105", 
    output_dir=NO_MEANING_DIR/"T1105", 
    logfile_name='security2', 
    parser_type="drain", 
)

Parsing file: ../data/no_meaning/T1105/buffer.csv
Total size after reading CSV: 1027687
Parsing done. [Time taken: 0:02:07.250112]

### HDFS

# 実験

### T1105(full)

In [4]:
# train
main.main_cli([
    "train",
    "bert/T1105(full)_time",           # conf/bert_config_name.yaml
    #"default.device_id=0",        # ここに好きな key=value を並べる
    #"default.epochs=10",
])

setup
Building Vocab

100%|██████████| 17727/17727 [00:00<00:00, 40687.86it/s]

VOCAB SIZE: 60
before filtering short session
train size  12763
valid size  1418
========================================

100%|██████████| 14181/14181 [00:04<00:00, 3290.77it/s]

========================================
Num of train seqs 12752
Num of valid seqs 1418
========================================

26it [00:04,  6.08it/s]

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/home/siwamura/My_lad/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3701, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_2425934/2109003172.py", line 2, in <module>
    main.main_cli([
  File "/home/siwamura/My_lad/src/main.py", line 360, in main_cli
    do_train(cfg)
  File "/home/siwamura/My_lad/src/main.py", line 74, in do_train
    train_loss = train(cfg, model, device, data_dict, optimizer, criterion)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/siwamura/My_lad/src/train_val.py", line None, in train
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/siwamura/My_lad/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 2201, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/siwamura/My_lad/.venv/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1193, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/siwamura/My_lad/.venv/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1064, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/siwamura/My_lad/.venv/lib/python3.11/site-packages/IPython/core/ultratb.py", line 872, in structured_traceback
    formatted_exceptions: list[list[str]] = self.format_exception_as_a_whole(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/siwamura/My_lad/.venv/lib/python3.11/site-packages/IPython/core/ultratb.py", line 784, in format_exception_as_a_whole
    frames.append(self.format_record(record))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/siwamura/My_lad/.venv/lib/python3.11/site-packages/IPython/core/ultratb.py", line 540, in format_record
    assert isinstance(frame_info.lineno, int)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

In [ ]:
# train
main.main_cli([
    "train",
    "bert/T1105(full)_fixed",           # conf/bert_config_name.yaml
    #"default.device_id=0",        # ここに好きな key=value を並べる
    #"default.epochs=10",
])

In [ ]:
# テスト
main.main_cli([
    "test",  # run_mode
    "outputs/logbert/bert_v2/T1105(full)_time/ver_2/ratio_0.8/seq_len_256/r_seed_31/weights/ValTotalbest.pth", # 重みファイルまでの相対パス
    "32",   # eval_batchsize
    "cuda:0",     # gpu
])

In [11]:
# テスト
main.main_cli([
    "test",  # run_mode
    "outputs/logbert/bert/T1105(full)_fixed/ver_2/ratio_0.8/seq_len_256/r_seed_31/weights/ValTotalbest.pth", # 重みファイルまでの相対パス
    "64",   # eval_batchsize
    "cuda:0",     # gpu
])

==================================================
outputs/logbert/bert/T1105(full)_fixed/ver_2/ratio_0.8/seq_len_256/r_seed_31
==================================================
cuda:0 cuda:0
Building Vocab

100%|██████████| 20532/20532 [00:00<00:00, 50144.78it/s]

VOCAB SIZE: 60

Processing normal test data: 100%|██████████| 4107/4107 [00:01<00:00, 3424.78it/s]
Processing abnormal test data: 100%|██████████| 20/20 [00:00<00:00, 3257.33it/s]
100%|██████████| 64/64 [00:02<00:00, 24.12it/s]
100%|██████████| 20/20 [00:00<00:00, 25.38it/s]

Saving test normal results
Saving test abnormal results
[seq_th, FP, TP, TN, FN, Precision, Recall, F1, TPR, FPR]
threshold=0.000['101.0000', '2.0000', '3995.0000', '18.0000', '1.9417', '10.0000', '3.2520', '10.0000', '2.4658']
threshold=0.010['101.0000', '2.0000', '3995.0000', '18.0000', '1.9417', '10.0000', '3.2520', '10.0000', '2.4658']
threshold=0.020['71.0000', '2.0000', '4025.0000', '18.0000', '2.7397', '10.0000', '4.3011', '10.0000', '1.7334']
threshold=0.030['56.0000', '2.0000', '4040.0000', '18.0000', '3.4483', '10.0000', '5.1282', '10.0000', '1.3672']
threshold=0.040['44.0000', '2.0000', '4052.0000', '18.0000', '4.3478', '10.0000', '6.0606', '10.0000', '1.0742']
threshold=0.050['39.0000', '1.0000', '4057.0000', '19.0000', '2.5000', '5.0000', '3.3333', '5.0000', '0.9521']
threshold=0.060['35.0000', '1.0000', '4061.0000', '19.0000', '2.7778', '5.0000', '3.5714', '5.0000', '0.8545']
threshold=0.070['29.0000', '0.0000', '4067.0000', '20.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.7080']
threshold=0.080['26.0000', '0.0000', '4070.0000', '20.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.6348']
threshold=0.090['22.0000', '0.0000', '4074.0000', '20.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.5371']
threshold=0.100['22.0000', '0.0000', '4074.0000', '20.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.5371']

### Integrated(T1105)

In [ ]:
# train
main.main_cli([
    "train",
    "bert/Integrated_T1105_fixed",           # conf/bert_config_name.yaml
    #"default.device_id=0",        # ここに好きな key=value を並べる
    #"default.epochs=10",
])

In [ ]:
# テスト
main.main_cli([
    "test",  # run_mode
    "outputs/logbert/bert_no_time/Integrated_fixed/T1105/ratio_0.8/seq_len_512/r_seed_31/weights/ValTotalbest.pth", # 重みファイルまでの相対パス
    "64",   # eval_batchsize
    "cuda:0",     # gpu
])

==================================================
outputs/logbert/bert_no_time/T1105/ver_2/ratio_0.8/seq_len_512/r_seed_31
==================================================
cuda:0 cuda:0
Building Vocab

100%|██████████| 4688/4688 [00:00<00:00, 22165.12it/s]

VOCAB SIZE: 60

Processing normal test data: 100%|██████████| 353/353 [00:00<00:00, 2388.37it/s]
Processing abnormal test data: 100%|██████████| 13/13 [00:00<00:00, 2218.94it/s]
100%|██████████| 5/5 [00:01<00:00,  4.90it/s]
100%|██████████| 13/13 [00:00<00:00, 16.35it/s]

Saving test normal results
Saving test abnormal results
[seq_th, FP, TP, TN, FN, Precision, Recall, F1, TPR, FPR]
threshold=0.000['17.0000', '5.0000', '303.0000', '8.0000', '22.7273', '38.4615', '28.5714', '38.4615', '5.3125']
threshold=0.010['12.0000', '4.0000', '308.0000', '9.0000', '25.0000', '30.7692', '27.5862', '30.7692', '3.7500']
threshold=0.020['11.0000', '2.0000', '309.0000', '11.0000', '15.3846', '15.3846', '15.3846', '15.3846', '3.4375']
threshold=0.030['10.0000', '0.0000', '310.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '3.1250']
threshold=0.040['9.0000', '0.0000', '311.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '2.8125']
threshold=0.050['8.0000', '0.0000', '312.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '2.5000']
threshold=0.060['8.0000', '0.0000', '312.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '2.5000']
threshold=0.070['7.0000', '0.0000', '313.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '2.1875']
threshold=0.080['6.0000', '0.0000', '314.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '1.8750']
threshold=0.090['4.0000', '0.0000', '316.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '1.2500']
threshold=0.100['3.0000', '0.0000', '317.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.9375']

### Integrated (WEB1)

In [5]:
# train
main.main_cli([
    "train",
    "bert/Integrated_WEB1_fixed",           # conf/bert_config_name.yaml
    #"default.device_id=0",        # ここに好きな key=value を並べる
    #"default.epochs=10",
])

setup
Building Vocab

100%|██████████| 4688/4688 [00:00<00:00, 26385.04it/s]

VOCAB SIZE: 60

before filtering short session
train size  11022
valid size  1224
========================================

100%|██████████| 12246/12246 [00:04<00:00, 2534.92it/s]

========================================
Num of train seqs 11022
Num of valid seqs 1224
========================================

344it [00:14, 23.03it/s]
38it [00:00, 75.59it/s]

epoch 1 || TRAIN_Loss:4.1992 ||VAL_Loss:4.0315
Best epoch = 1

344it [00:14, 23.41it/s]
38it [00:00, 71.30it/s]

epoch 2 || TRAIN_Loss:2.6400 ||VAL_Loss:1.4923
Best epoch = 2

344it [00:14, 23.14it/s]
38it [00:00, 71.25it/s]

epoch 3 || TRAIN_Loss:1.3791 ||VAL_Loss:1.2021
Best epoch = 3

344it [00:14, 23.15it/s]
38it [00:00, 72.37it/s]

epoch 4 || TRAIN_Loss:1.2404 ||VAL_Loss:1.1445
Best epoch = 4

344it [00:14, 23.30it/s]
38it [00:00, 69.81it/s]

epoch 5 || TRAIN_Loss:1.2006 ||VAL_Loss:1.1322
Best epoch = 5

344it [00:14, 23.26it/s]
38it [00:00, 73.10it/s]

epoch 6 || TRAIN_Loss:1.1827 ||VAL_Loss:1.1138
Best epoch = 6

344it [00:14, 23.12it/s]
38it [00:00, 69.78it/s]

epoch 7 || TRAIN_Loss:1.1724 ||VAL_Loss:1.1139
Best epoch = 6

344it [00:14, 23.10it/s]
38it [00:00, 68.52it/s]

epoch 8 || TRAIN_Loss:1.1679 ||VAL_Loss:1.1132
Best epoch = 8

344it [00:14, 23.11it/s]
38it [00:00, 71.34it/s]

epoch 9 || TRAIN_Loss:1.1628 ||VAL_Loss:1.1084
Best epoch = 9

344it [00:14, 23.11it/s]
38it [00:00, 68.76it/s]

epoch 10 || TRAIN_Loss:1.1602 ||VAL_Loss:1.1069
Best epoch = 10

344it [00:14, 23.13it/s]
38it [00:00, 71.13it/s]

epoch 11 || TRAIN_Loss:1.1568 ||VAL_Loss:1.1034
Best epoch = 11

344it [00:14, 22.98it/s]
38it [00:00, 71.86it/s]

epoch 12 || TRAIN_Loss:1.1531 ||VAL_Loss:1.1034
Best epoch = 11

344it [00:14, 22.98it/s]
38it [00:00, 72.61it/s]

epoch 13 || TRAIN_Loss:1.1505 ||VAL_Loss:1.1092
Best epoch = 11

344it [00:14, 22.95it/s]
38it [00:00, 69.11it/s]

epoch 14 || TRAIN_Loss:1.1474 ||VAL_Loss:1.1017
Best epoch = 14

344it [00:15, 22.81it/s]
38it [00:00, 71.04it/s]

epoch 15 || TRAIN_Loss:1.1447 ||VAL_Loss:1.1001
Best epoch = 15

344it [00:15, 22.89it/s]
38it [00:00, 68.13it/s]

epoch 16 || TRAIN_Loss:1.1409 ||VAL_Loss:1.0968
Best epoch = 16

344it [00:15, 22.89it/s]
38it [00:00, 70.24it/s]

epoch 17 || TRAIN_Loss:1.1380 ||VAL_Loss:1.0988
Best epoch = 16

344it [00:15, 22.91it/s]
38it [00:00, 70.96it/s]

epoch 18 || TRAIN_Loss:1.1333 ||VAL_Loss:1.0933
Best epoch = 18

344it [00:15, 22.83it/s]
38it [00:00, 71.16it/s]

epoch 19 || TRAIN_Loss:1.1285 ||VAL_Loss:1.0948
Best epoch = 18

344it [00:15, 22.80it/s]
38it [00:00, 71.79it/s]

epoch 20 || TRAIN_Loss:1.1240 ||VAL_Loss:1.0879
Best epoch = 20

344it [00:15, 22.77it/s]
38it [00:00, 67.81it/s]

epoch 21 || TRAIN_Loss:1.1195 ||VAL_Loss:1.0864
Best epoch = 21

344it [00:15, 22.74it/s]
38it [00:00, 68.95it/s]

epoch 22 || TRAIN_Loss:1.1151 ||VAL_Loss:1.0805
Best epoch = 22

344it [00:15, 22.84it/s]
38it [00:00, 71.03it/s]

epoch 23 || TRAIN_Loss:1.1100 ||VAL_Loss:1.0792
Best epoch = 23

344it [00:15, 22.79it/s]
38it [00:00, 72.79it/s]

epoch 24 || TRAIN_Loss:1.1064 ||VAL_Loss:1.0721
Best epoch = 24

344it [00:15, 22.86it/s]
38it [00:00, 71.49it/s]

epoch 25 || TRAIN_Loss:1.1035 ||VAL_Loss:1.0771
Best epoch = 24

344it [00:15, 22.88it/s]
38it [00:00, 68.91it/s]

epoch 26 || TRAIN_Loss:1.1005 ||VAL_Loss:1.0711
Best epoch = 26

344it [00:15, 22.88it/s]
38it [00:00, 67.77it/s]

epoch 27 || TRAIN_Loss:1.0970 ||VAL_Loss:1.0673
Best epoch = 27

344it [00:15, 22.88it/s]
38it [00:00, 66.36it/s]

epoch 28 || TRAIN_Loss:1.0935 ||VAL_Loss:1.0682
Best epoch = 27

344it [00:15, 22.93it/s]
38it [00:00, 71.00it/s]

epoch 29 || TRAIN_Loss:1.0910 ||VAL_Loss:1.0640
Best epoch = 29

344it [00:15, 22.89it/s]
38it [00:00, 68.89it/s]

epoch 30 || TRAIN_Loss:1.0892 ||VAL_Loss:1.0623
Best epoch = 30

344it [00:15, 22.79it/s]
38it [00:00, 69.11it/s]

epoch 31 || TRAIN_Loss:1.0869 ||VAL_Loss:1.0660
Best epoch = 30

344it [00:15, 22.88it/s]
38it [00:00, 70.03it/s]

epoch 32 || TRAIN_Loss:1.0865 ||VAL_Loss:1.0635
Best epoch = 30

344it [00:15, 22.89it/s]
38it [00:00, 66.81it/s]

epoch 33 || TRAIN_Loss:1.0835 ||VAL_Loss:1.0622
Best epoch = 33

344it [00:14, 22.94it/s]
38it [00:00, 70.14it/s]

epoch 34 || TRAIN_Loss:1.0825 ||VAL_Loss:1.0572
Best epoch = 34

344it [00:15, 22.83it/s]
38it [00:00, 68.75it/s]

epoch 35 || TRAIN_Loss:1.0820 ||VAL_Loss:1.0590
Best epoch = 34

344it [00:15, 22.80it/s]
38it [00:00, 71.10it/s]

epoch 36 || TRAIN_Loss:1.0801 ||VAL_Loss:1.0572
Best epoch = 34

344it [00:15, 22.84it/s]
38it [00:00, 71.07it/s]

epoch 37 || TRAIN_Loss:1.0798 ||VAL_Loss:1.0548
Best epoch = 37

344it [00:15, 22.93it/s]
38it [00:00, 73.57it/s]

epoch 38 || TRAIN_Loss:1.0788 ||VAL_Loss:1.0549
Best epoch = 37

344it [00:15, 22.93it/s]
38it [00:00, 66.94it/s]

epoch 39 || TRAIN_Loss:1.0776 ||VAL_Loss:1.0544
Best epoch = 39

344it [00:15, 22.83it/s]
38it [00:00, 67.41it/s]

epoch 40 || TRAIN_Loss:1.0764 ||VAL_Loss:1.0529
Best epoch = 40

344it [00:15, 22.92it/s]
38it [00:00, 70.40it/s]

epoch 41 || TRAIN_Loss:1.0763 ||VAL_Loss:1.0508
Best epoch = 41

344it [00:15, 22.85it/s]
38it [00:00, 69.02it/s]

epoch 42 || TRAIN_Loss:1.0752 ||VAL_Loss:1.0530
Best epoch = 41

344it [00:15, 22.92it/s]
38it [00:00, 68.96it/s]

epoch 43 || TRAIN_Loss:1.0726 ||VAL_Loss:1.0501
Best epoch = 43

344it [00:15, 22.85it/s]
38it [00:00, 65.89it/s]

epoch 44 || TRAIN_Loss:1.0729 ||VAL_Loss:1.0502
Best epoch = 43

344it [00:15, 22.91it/s]
38it [00:00, 71.48it/s]

epoch 45 || TRAIN_Loss:1.0716 ||VAL_Loss:1.0495
Best epoch = 45

344it [00:15, 22.82it/s]
38it [00:00, 67.62it/s]

epoch 46 || TRAIN_Loss:1.0701 ||VAL_Loss:1.0505
Best epoch = 45

344it [00:14, 22.96it/s]
38it [00:00, 66.66it/s]

epoch 47 || TRAIN_Loss:1.0699 ||VAL_Loss:1.0452
Best epoch = 47

344it [00:14, 22.95it/s]
38it [00:00, 71.56it/s]

epoch 48 || TRAIN_Loss:1.0680 ||VAL_Loss:1.0465
Best epoch = 47

344it [00:14, 22.96it/s]
38it [00:00, 71.41it/s]

epoch 49 || TRAIN_Loss:1.0669 ||VAL_Loss:1.0420
Best epoch = 49

344it [00:15, 22.77it/s]
38it [00:00, 71.71it/s]

epoch 50 || TRAIN_Loss:1.0652 ||VAL_Loss:1.0455
Best epoch = 49

344it [00:15, 22.82it/s]
38it [00:00, 69.10it/s]

epoch 51 || TRAIN_Loss:1.0626 ||VAL_Loss:1.0381
Best epoch = 51

344it [00:15, 22.87it/s]
38it [00:00, 70.72it/s]

epoch 52 || TRAIN_Loss:1.0610 ||VAL_Loss:1.0402
Best epoch = 51

344it [00:15, 22.90it/s]
38it [00:00, 72.34it/s]

epoch 53 || TRAIN_Loss:1.0594 ||VAL_Loss:1.0392
Best epoch = 51

344it [00:15, 22.92it/s]
38it [00:00, 72.88it/s]

epoch 54 || TRAIN_Loss:1.0604 ||VAL_Loss:1.0415
Best epoch = 51

344it [00:14, 22.95it/s]
38it [00:00, 71.14it/s]

epoch 55 || TRAIN_Loss:1.0586 ||VAL_Loss:1.0386
Best epoch = 51

344it [00:15, 22.85it/s]
38it [00:00, 69.74it/s]

epoch 56 || TRAIN_Loss:1.0572 ||VAL_Loss:1.0366
Best epoch = 56

344it [00:15, 22.85it/s]
38it [00:00, 67.31it/s]

epoch 57 || TRAIN_Loss:1.0568 ||VAL_Loss:1.0358
Best epoch = 57

344it [00:15, 22.77it/s]
38it [00:00, 66.49it/s]

epoch 58 || TRAIN_Loss:1.0565 ||VAL_Loss:1.0347
Best epoch = 58

344it [00:15, 22.85it/s]
38it [00:00, 65.02it/s]

epoch 59 || TRAIN_Loss:1.0557 ||VAL_Loss:1.0331
Best epoch = 59

344it [00:15, 22.91it/s]
38it [00:00, 65.60it/s]

epoch 60 || TRAIN_Loss:1.0545 ||VAL_Loss:1.0401
Best epoch = 59

344it [00:15, 22.91it/s]
38it [00:00, 67.56it/s]

epoch 61 || TRAIN_Loss:1.0531 ||VAL_Loss:1.0390
Best epoch = 59

344it [00:15, 22.86it/s]
38it [00:00, 69.33it/s]

epoch 62 || TRAIN_Loss:1.0517 ||VAL_Loss:1.0432
Best epoch = 59

344it [00:15, 22.85it/s]
38it [00:00, 70.98it/s]

epoch 63 || TRAIN_Loss:1.0520 ||VAL_Loss:1.0314
Best epoch = 63

344it [00:15, 22.75it/s]
38it [00:00, 68.39it/s]

epoch 64 || TRAIN_Loss:1.0507 ||VAL_Loss:1.0380
Best epoch = 63

344it [00:15, 22.82it/s]
38it [00:00, 68.17it/s]

epoch 65 || TRAIN_Loss:1.0491 ||VAL_Loss:1.0320
Best epoch = 63

344it [00:15, 22.78it/s]
38it [00:00, 65.28it/s]

epoch 66 || TRAIN_Loss:1.0494 ||VAL_Loss:1.0299
Best epoch = 66

344it [00:15, 22.89it/s]
38it [00:00, 71.59it/s]

epoch 67 || TRAIN_Loss:1.0477 ||VAL_Loss:1.0303
Best epoch = 66

344it [00:15, 22.75it/s]
38it [00:00, 72.33it/s]

epoch 68 || TRAIN_Loss:1.0438 ||VAL_Loss:1.0270
Best epoch = 68

344it [00:15, 22.79it/s]
38it [00:00, 69.37it/s]

epoch 69 || TRAIN_Loss:1.0428 ||VAL_Loss:1.0213
Best epoch = 69

344it [00:15, 22.82it/s]
38it [00:00, 66.62it/s]

epoch 70 || TRAIN_Loss:1.0400 ||VAL_Loss:1.0166
Best epoch = 70

344it [00:15, 22.85it/s]
38it [00:00, 66.15it/s]

epoch 71 || TRAIN_Loss:1.0361 ||VAL_Loss:1.0198
Best epoch = 70

344it [00:15, 22.82it/s]
38it [00:00, 66.95it/s]

epoch 72 || TRAIN_Loss:1.0318 ||VAL_Loss:1.0064
Best epoch = 72

344it [00:15, 22.92it/s]
38it [00:00, 72.35it/s]

epoch 73 || TRAIN_Loss:1.0261 ||VAL_Loss:1.0050
Best epoch = 73

344it [00:15, 22.82it/s]
38it [00:00, 68.79it/s]

epoch 74 || TRAIN_Loss:1.0174 ||VAL_Loss:0.9917
Best epoch = 74

344it [00:15, 22.80it/s]
38it [00:00, 69.17it/s]

epoch 75 || TRAIN_Loss:1.0082 ||VAL_Loss:0.9796
Best epoch = 75

344it [00:15, 22.84it/s]
38it [00:00, 64.96it/s]

epoch 76 || TRAIN_Loss:0.9937 ||VAL_Loss:0.9617
Best epoch = 76

344it [00:15, 22.89it/s]
38it [00:00, 70.98it/s]

epoch 77 || TRAIN_Loss:0.9805 ||VAL_Loss:0.9555
Best epoch = 77

344it [00:15, 22.87it/s]
38it [00:00, 68.69it/s]

epoch 78 || TRAIN_Loss:0.9689 ||VAL_Loss:0.9530
Best epoch = 78

344it [00:15, 22.81it/s]
38it [00:00, 72.05it/s]

epoch 79 || TRAIN_Loss:0.9617 ||VAL_Loss:0.9441
Best epoch = 79

344it [00:15, 22.85it/s]
38it [00:00, 67.95it/s]

epoch 80 || TRAIN_Loss:0.9554 ||VAL_Loss:0.9456
Best epoch = 79

344it [00:15, 22.88it/s]
38it [00:00, 70.42it/s]

epoch 81 || TRAIN_Loss:0.9504 ||VAL_Loss:0.9396
Best epoch = 81

344it [00:15, 22.83it/s]
38it [00:00, 66.22it/s]

epoch 82 || TRAIN_Loss:0.9461 ||VAL_Loss:0.9375
Best epoch = 82

344it [00:15, 22.72it/s]
38it [00:00, 66.44it/s]

epoch 83 || TRAIN_Loss:0.9437 ||VAL_Loss:0.9314
Best epoch = 83

344it [00:15, 22.86it/s]
38it [00:00, 65.26it/s]

epoch 84 || TRAIN_Loss:0.9416 ||VAL_Loss:0.9298
Best epoch = 84

344it [00:14, 22.94it/s]
38it [00:00, 67.76it/s]

epoch 85 || TRAIN_Loss:0.9393 ||VAL_Loss:0.9289
Best epoch = 85

344it [00:15, 22.77it/s]
38it [00:00, 67.44it/s]

epoch 86 || TRAIN_Loss:0.9383 ||VAL_Loss:0.9263
Best epoch = 86

344it [00:15, 22.88it/s]
38it [00:00, 68.28it/s]

epoch 87 || TRAIN_Loss:0.9360 ||VAL_Loss:0.9242
Best epoch = 87

344it [00:15, 22.80it/s]
38it [00:00, 67.28it/s]

epoch 88 || TRAIN_Loss:0.9333 ||VAL_Loss:0.9252
Best epoch = 87

344it [00:15, 22.84it/s]
38it [00:00, 68.34it/s]

epoch 89 || TRAIN_Loss:0.9351 ||VAL_Loss:0.9259
Best epoch = 87

344it [00:15, 22.80it/s]
38it [00:00, 69.22it/s]

epoch 90 || TRAIN_Loss:0.9335 ||VAL_Loss:0.9260
Best epoch = 87

344it [00:15, 22.83it/s]
38it [00:00, 69.14it/s]

epoch 91 || TRAIN_Loss:0.9324 ||VAL_Loss:0.9217
Best epoch = 91

344it [00:15, 22.77it/s]
38it [00:00, 67.92it/s]

epoch 92 || TRAIN_Loss:0.9316 ||VAL_Loss:0.9247
Best epoch = 91

344it [00:15, 22.84it/s]
38it [00:00, 72.54it/s]

epoch 93 || TRAIN_Loss:0.9315 ||VAL_Loss:0.9211
Best epoch = 93

344it [00:15, 22.86it/s]
38it [00:00, 71.68it/s]

epoch 94 || TRAIN_Loss:0.9292 ||VAL_Loss:0.9174
Best epoch = 94

344it [00:15, 22.88it/s]
38it [00:00, 68.23it/s]

epoch 95 || TRAIN_Loss:0.9306 ||VAL_Loss:0.9191
Best epoch = 94

344it [00:15, 22.87it/s]
38it [00:00, 72.56it/s]

epoch 96 || TRAIN_Loss:0.9296 ||VAL_Loss:0.9206
Best epoch = 94

344it [00:14, 22.95it/s]
38it [00:00, 72.44it/s]

epoch 97 || TRAIN_Loss:0.9300 ||VAL_Loss:0.9207
Best epoch = 94

344it [00:15, 22.85it/s]
38it [00:00, 68.26it/s]

epoch 98 || TRAIN_Loss:0.9292 ||VAL_Loss:0.9205
Best epoch = 94

344it [00:15, 22.93it/s]
38it [00:00, 67.82it/s]

epoch 99 || TRAIN_Loss:0.9284 ||VAL_Loss:0.9204
Best epoch = 94

344it [00:15, 22.89it/s]
38it [00:00, 71.49it/s]

epoch 100 || TRAIN_Loss:0.9294 ||VAL_Loss:0.9199
Best epoch = 94

344it [00:15, 22.86it/s]
38it [00:00, 69.42it/s]

epoch 101 || TRAIN_Loss:0.9289 ||VAL_Loss:0.9184
Best epoch = 94

344it [00:15, 22.90it/s]
38it [00:00, 67.55it/s]

epoch 102 || TRAIN_Loss:0.9288 ||VAL_Loss:0.9208
Best epoch = 94

344it [00:14, 22.94it/s]
38it [00:00, 68.83it/s]

epoch 103 || TRAIN_Loss:0.9278 ||VAL_Loss:0.9207
Best epoch = 94

344it [00:15, 22.93it/s]
38it [00:00, 71.19it/s]

epoch 104 || TRAIN_Loss:0.9277 ||VAL_Loss:0.9187
Best epoch = 94

344it [00:14, 22.93it/s]
38it [00:00, 71.64it/s]

epoch 105 || TRAIN_Loss:0.9271 ||VAL_Loss:0.9191
Best epoch = 94

344it [00:15, 22.92it/s]
38it [00:00, 66.84it/s]

epoch 106 || TRAIN_Loss:0.9272 ||VAL_Loss:0.9170
Best epoch = 106

344it [00:15, 22.87it/s]
38it [00:00, 65.63it/s]

epoch 107 || TRAIN_Loss:0.9266 ||VAL_Loss:0.9150
Best epoch = 107

344it [00:15, 22.85it/s]
38it [00:00, 69.30it/s]

epoch 108 || TRAIN_Loss:0.9271 ||VAL_Loss:0.9178
Best epoch = 107

344it [00:15, 22.88it/s]
38it [00:00, 67.76it/s]

epoch 109 || TRAIN_Loss:0.9264 ||VAL_Loss:0.9215
Best epoch = 107

344it [00:15, 22.84it/s]
38it [00:00, 68.06it/s]

epoch 110 || TRAIN_Loss:0.9262 ||VAL_Loss:0.9180
Best epoch = 107

344it [00:15, 22.91it/s]
38it [00:00, 65.68it/s]

epoch 111 || TRAIN_Loss:0.9258 ||VAL_Loss:0.9172
Best epoch = 107

344it [00:15, 22.86it/s]
38it [00:00, 66.08it/s]

epoch 112 || TRAIN_Loss:0.9269 ||VAL_Loss:0.9153
Best epoch = 107

344it [00:15, 22.89it/s]
38it [00:00, 68.18it/s]

epoch 113 || TRAIN_Loss:0.9259 ||VAL_Loss:0.9197
Best epoch = 107

344it [00:15, 22.80it/s]
38it [00:00, 69.24it/s]

epoch 114 || TRAIN_Loss:0.9256 ||VAL_Loss:0.9159
Best epoch = 107

344it [00:15, 22.82it/s]
38it [00:00, 67.97it/s]

epoch 115 || TRAIN_Loss:0.9256 ||VAL_Loss:0.9140
Best epoch = 115

344it [00:15, 22.80it/s]
38it [00:00, 71.01it/s]

epoch 116 || TRAIN_Loss:0.9259 ||VAL_Loss:0.9187
Best epoch = 115

344it [00:15, 22.89it/s]
38it [00:00, 69.10it/s]

epoch 117 || TRAIN_Loss:0.9246 ||VAL_Loss:0.9121
Best epoch = 117

344it [00:15, 22.88it/s]
38it [00:00, 71.39it/s]

epoch 118 || TRAIN_Loss:0.9255 ||VAL_Loss:0.9152
Best epoch = 117

344it [00:15, 22.82it/s]
38it [00:00, 72.41it/s]

epoch 119 || TRAIN_Loss:0.9241 ||VAL_Loss:0.9176
Best epoch = 117

344it [00:15, 22.92it/s]
38it [00:00, 71.93it/s]

epoch 120 || TRAIN_Loss:0.9249 ||VAL_Loss:0.9152
Best epoch = 117

344it [00:15, 22.82it/s]
38it [00:00, 68.91it/s]

epoch 121 || TRAIN_Loss:0.9257 ||VAL_Loss:0.9156
Best epoch = 117

344it [00:15, 22.87it/s]
38it [00:00, 67.11it/s]

epoch 122 || TRAIN_Loss:0.9250 ||VAL_Loss:0.9158
Best epoch = 117

344it [00:14, 22.97it/s]
38it [00:00, 67.06it/s]

epoch 123 || TRAIN_Loss:0.9249 ||VAL_Loss:0.9168
Best epoch = 117

344it [00:15, 22.83it/s]
38it [00:00, 65.84it/s]

epoch 124 || TRAIN_Loss:0.9249 ||VAL_Loss:0.9118
Best epoch = 124

344it [00:15, 22.82it/s]
38it [00:00, 72.67it/s]

epoch 125 || TRAIN_Loss:0.9251 ||VAL_Loss:0.9116
Best epoch = 125

344it [00:15, 22.87it/s]
38it [00:00, 66.91it/s]

epoch 126 || TRAIN_Loss:0.9237 ||VAL_Loss:0.9146
Best epoch = 125

344it [00:15, 22.84it/s]
38it [00:00, 73.15it/s]

epoch 127 || TRAIN_Loss:0.9235 ||VAL_Loss:0.9140
Best epoch = 125

344it [00:15, 22.92it/s]
38it [00:00, 71.60it/s]

epoch 128 || TRAIN_Loss:0.9240 ||VAL_Loss:0.9142
Best epoch = 125

344it [00:15, 22.86it/s]
38it [00:00, 71.54it/s]

epoch 129 || TRAIN_Loss:0.9243 ||VAL_Loss:0.9138
Best epoch = 125

344it [00:14, 22.95it/s]
38it [00:00, 71.36it/s]

epoch 130 || TRAIN_Loss:0.9244 ||VAL_Loss:0.9123
Best epoch = 125

344it [00:15, 22.92it/s]
38it [00:00, 67.99it/s]

epoch 131 || TRAIN_Loss:0.9238 ||VAL_Loss:0.9159
Best epoch = 125

344it [00:15, 22.93it/s]
38it [00:00, 65.18it/s]

epoch 132 || TRAIN_Loss:0.9236 ||VAL_Loss:0.9118
Best epoch = 125

344it [00:15, 22.92it/s]
38it [00:00, 72.97it/s]

epoch 133 || TRAIN_Loss:0.9230 ||VAL_Loss:0.9161
Best epoch = 125

344it [00:15, 22.93it/s]
38it [00:00, 66.07it/s]

epoch 134 || TRAIN_Loss:0.9224 ||VAL_Loss:0.9147
Best epoch = 125

344it [00:15, 22.93it/s]
38it [00:00, 68.04it/s]

epoch 135 || TRAIN_Loss:0.9232 ||VAL_Loss:0.9145
Best epoch = 125

344it [00:15, 22.80it/s]
38it [00:00, 66.10it/s]

epoch 136 || TRAIN_Loss:0.9231 ||VAL_Loss:0.9170
Best epoch = 125

344it [00:14, 22.96it/s]
38it [00:00, 66.76it/s]

epoch 137 || TRAIN_Loss:0.9224 ||VAL_Loss:0.9122
Best epoch = 125

344it [00:14, 22.96it/s]
38it [00:00, 69.18it/s]

epoch 138 || TRAIN_Loss:0.9243 ||VAL_Loss:0.9126
Best epoch = 125

344it [00:15, 22.87it/s]
38it [00:00, 70.54it/s]

epoch 139 || TRAIN_Loss:0.9228 ||VAL_Loss:0.9164
Best epoch = 125

344it [00:15, 22.88it/s]
38it [00:00, 68.17it/s]

epoch 140 || TRAIN_Loss:0.9230 ||VAL_Loss:0.9136
Best epoch = 125

344it [00:15, 22.91it/s]
38it [00:00, 71.07it/s]

epoch 141 || TRAIN_Loss:0.9237 ||VAL_Loss:0.9164
Best epoch = 125

344it [00:15, 22.87it/s]
38it [00:00, 71.56it/s]

epoch 142 || TRAIN_Loss:0.9232 ||VAL_Loss:0.9114
Best epoch = 142

344it [00:15, 22.86it/s]
38it [00:00, 70.20it/s]

epoch 143 || TRAIN_Loss:0.9221 ||VAL_Loss:0.9160
Best epoch = 142

344it [00:14, 22.94it/s]
38it [00:00, 70.12it/s]

epoch 144 || TRAIN_Loss:0.9224 ||VAL_Loss:0.9137
Best epoch = 142

344it [00:15, 22.88it/s]
38it [00:00, 66.53it/s]

epoch 145 || TRAIN_Loss:0.9231 ||VAL_Loss:0.9119
Best epoch = 142

344it [00:15, 22.92it/s]
38it [00:00, 68.51it/s]

epoch 146 || TRAIN_Loss:0.9227 ||VAL_Loss:0.9125
Best epoch = 142

344it [00:14, 22.97it/s]
38it [00:00, 67.03it/s]

epoch 147 || TRAIN_Loss:0.9218 ||VAL_Loss:0.9138
Best epoch = 142

344it [00:14, 22.96it/s]
38it [00:00, 66.63it/s]

epoch 148 || TRAIN_Loss:0.9226 ||VAL_Loss:0.9132
Best epoch = 142

344it [00:14, 22.94it/s]
38it [00:00, 71.41it/s]

epoch 149 || TRAIN_Loss:0.9211 ||VAL_Loss:0.9132
Best epoch = 142

344it [00:15, 22.91it/s]
38it [00:00, 69.53it/s]

epoch 150 || TRAIN_Loss:0.9219 ||VAL_Loss:0.9133
Best epoch = 142

344it [00:14, 22.96it/s]
38it [00:00, 68.42it/s]

epoch 151 || TRAIN_Loss:0.9216 ||VAL_Loss:0.9110
Best epoch = 151

344it [00:15, 22.82it/s]
38it [00:00, 69.94it/s]

epoch 152 || TRAIN_Loss:0.9225 ||VAL_Loss:0.9166
Best epoch = 151

344it [00:15, 22.90it/s]
38it [00:00, 64.78it/s]

epoch 153 || TRAIN_Loss:0.9222 ||VAL_Loss:0.9114
Best epoch = 151

344it [00:15, 22.92it/s]
38it [00:00, 68.58it/s]

epoch 154 || TRAIN_Loss:0.9214 ||VAL_Loss:0.9115
Best epoch = 151

344it [00:15, 22.86it/s]
38it [00:00, 69.96it/s]

epoch 155 || TRAIN_Loss:0.9218 ||VAL_Loss:0.9133
Best epoch = 151

344it [00:15, 22.88it/s]
38it [00:00, 69.33it/s]

epoch 156 || TRAIN_Loss:0.9225 ||VAL_Loss:0.9131
Best epoch = 151

344it [00:15, 22.93it/s]
38it [00:00, 66.37it/s]

epoch 157 || TRAIN_Loss:0.9211 ||VAL_Loss:0.9120
Best epoch = 151

344it [00:15, 22.83it/s]
38it [00:00, 67.32it/s]

epoch 158 || TRAIN_Loss:0.9213 ||VAL_Loss:0.9116
Best epoch = 151

344it [00:15, 22.79it/s]
38it [00:00, 70.05it/s]

epoch 159 || TRAIN_Loss:0.9218 ||VAL_Loss:0.9113
Best epoch = 151

344it [00:15, 22.91it/s]
38it [00:00, 64.51it/s]

epoch 160 || TRAIN_Loss:0.9219 ||VAL_Loss:0.9167
Best epoch = 151

344it [00:15, 22.87it/s]
38it [00:00, 66.26it/s]

epoch 161 || TRAIN_Loss:0.9205 ||VAL_Loss:0.9132
Best epoch = 151

344it [00:15, 22.87it/s]
38it [00:00, 68.24it/s]

epoch 162 || TRAIN_Loss:0.9215 ||VAL_Loss:0.9145
Best epoch = 151

344it [00:15, 22.86it/s]
38it [00:00, 67.47it/s]

epoch 163 || TRAIN_Loss:0.9205 ||VAL_Loss:0.9137
Best epoch = 151

344it [00:15, 22.84it/s]
38it [00:00, 69.92it/s]

epoch 164 || TRAIN_Loss:0.9216 ||VAL_Loss:0.9135
Best epoch = 151

344it [00:15, 22.92it/s]
38it [00:00, 65.41it/s]

epoch 165 || TRAIN_Loss:0.9213 ||VAL_Loss:0.9092
Best epoch = 165

344it [00:14, 22.94it/s]
38it [00:00, 69.67it/s]

epoch 166 || TRAIN_Loss:0.9213 ||VAL_Loss:0.9113
Best epoch = 165

344it [00:14, 22.96it/s]
38it [00:00, 70.58it/s]

epoch 167 || TRAIN_Loss:0.9220 ||VAL_Loss:0.9119
Best epoch = 165

344it [00:14, 22.95it/s]
38it [00:00, 67.11it/s]

epoch 168 || TRAIN_Loss:0.9221 ||VAL_Loss:0.9094
Best epoch = 165

344it [00:15, 22.93it/s]
38it [00:00, 70.38it/s]

epoch 169 || TRAIN_Loss:0.9212 ||VAL_Loss:0.9101
Best epoch = 165

344it [00:14, 22.97it/s]
38it [00:00, 67.20it/s]

epoch 170 || TRAIN_Loss:0.9214 ||VAL_Loss:0.9119
Best epoch = 165

344it [00:14, 22.96it/s]
38it [00:00, 71.53it/s]

epoch 171 || TRAIN_Loss:0.9206 ||VAL_Loss:0.9129
Best epoch = 165

344it [00:15, 22.89it/s]
38it [00:00, 68.81it/s]

epoch 172 || TRAIN_Loss:0.9221 ||VAL_Loss:0.9110
Best epoch = 165

344it [00:14, 22.96it/s]
38it [00:00, 70.13it/s]

epoch 173 || TRAIN_Loss:0.9204 ||VAL_Loss:0.9120
Best epoch = 165

344it [00:14, 22.95it/s]
38it [00:00, 66.41it/s]

epoch 174 || TRAIN_Loss:0.9216 ||VAL_Loss:0.9108
Best epoch = 165

344it [00:14, 22.94it/s]
38it [00:00, 72.02it/s]

epoch 175 || TRAIN_Loss:0.9209 ||VAL_Loss:0.9164
Best epoch = 165

344it [00:15, 22.87it/s]
38it [00:00, 65.78it/s]

epoch 176 || TRAIN_Loss:0.9218 ||VAL_Loss:0.9131
Best epoch = 165

344it [00:15, 22.89it/s]
38it [00:00, 71.04it/s]

epoch 177 || TRAIN_Loss:0.9202 ||VAL_Loss:0.9118
Best epoch = 165

344it [00:14, 23.01it/s]
38it [00:00, 70.07it/s]

epoch 178 || TRAIN_Loss:0.9209 ||VAL_Loss:0.9092
Best epoch = 178

344it [00:15, 22.86it/s]
38it [00:00, 67.65it/s]

epoch 179 || TRAIN_Loss:0.9218 ||VAL_Loss:0.9145
Best epoch = 178

344it [00:15, 22.80it/s]
38it [00:00, 65.79it/s]

epoch 180 || TRAIN_Loss:0.9210 ||VAL_Loss:0.9134
Best epoch = 178

344it [00:15, 22.86it/s]
38it [00:00, 65.26it/s]

epoch 181 || TRAIN_Loss:0.9212 ||VAL_Loss:0.9137
Best epoch = 178

344it [00:15, 22.88it/s]
38it [00:00, 70.36it/s]

epoch 182 || TRAIN_Loss:0.9208 ||VAL_Loss:0.9128
Best epoch = 178

344it [00:15, 22.92it/s]
38it [00:00, 67.10it/s]

epoch 183 || TRAIN_Loss:0.9215 ||VAL_Loss:0.9139
Best epoch = 178

344it [00:15, 22.91it/s]
38it [00:00, 72.19it/s]

epoch 184 || TRAIN_Loss:0.9222 ||VAL_Loss:0.9125
Best epoch = 178

344it [00:15, 22.91it/s]
38it [00:00, 68.22it/s]

epoch 185 || TRAIN_Loss:0.9200 ||VAL_Loss:0.9127
Best epoch = 178

344it [00:15, 22.87it/s]
38it [00:00, 69.26it/s]

epoch 186 || TRAIN_Loss:0.9198 ||VAL_Loss:0.9141
Best epoch = 178

344it [00:14, 22.95it/s]
38it [00:00, 69.57it/s]

epoch 187 || TRAIN_Loss:0.9213 ||VAL_Loss:0.9123
Best epoch = 178

344it [00:15, 22.89it/s]
38it [00:00, 64.99it/s]

epoch 188 || TRAIN_Loss:0.9213 ||VAL_Loss:0.9144
Best epoch = 178

344it [00:15, 22.92it/s]
38it [00:00, 66.55it/s]

epoch 189 || TRAIN_Loss:0.9217 ||VAL_Loss:0.9117
Best epoch = 178

344it [00:15, 22.92it/s]
38it [00:00, 66.87it/s]

epoch 190 || TRAIN_Loss:0.9212 ||VAL_Loss:0.9143
Best epoch = 178

344it [00:15, 22.89it/s]
38it [00:00, 70.03it/s]

epoch 191 || TRAIN_Loss:0.9203 ||VAL_Loss:0.9093
Best epoch = 178

344it [00:15, 22.89it/s]
38it [00:00, 69.12it/s]

epoch 192 || TRAIN_Loss:0.9211 ||VAL_Loss:0.9094
Best epoch = 178

344it [00:15, 22.90it/s]
38it [00:00, 67.89it/s]

epoch 193 || TRAIN_Loss:0.9218 ||VAL_Loss:0.9161
Best epoch = 178

344it [00:15, 22.90it/s]
38it [00:00, 65.66it/s]

epoch 194 || TRAIN_Loss:0.9214 ||VAL_Loss:0.9158
Best epoch = 178

344it [00:15, 22.92it/s]
38it [00:00, 68.62it/s]

epoch 195 || TRAIN_Loss:0.9207 ||VAL_Loss:0.9130
Best epoch = 178

344it [00:14, 22.95it/s]
38it [00:00, 71.11it/s]

epoch 196 || TRAIN_Loss:0.9203 ||VAL_Loss:0.9092
Best epoch = 178

344it [00:14, 22.93it/s]
38it [00:00, 68.91it/s]

epoch 197 || TRAIN_Loss:0.9209 ||VAL_Loss:0.9117
Best epoch = 178

344it [00:15, 22.92it/s]
38it [00:00, 65.90it/s]

epoch 198 || TRAIN_Loss:0.9211 ||VAL_Loss:0.9135
Early stopping at epoch 198 (best = 178)

In [6]:
# テスト
main.main_cli([
    "test",  # run_mode
    "outputs/logbert/bert_no_time/Integrated_fixed/WEB1/ratio_0.8/seq_len_256/r_seed_31/weights/ValTotalbest.pth", # 重みファイルまでの相対パス
    "64",   # eval_batchsize
    "cuda:0",     # gpu
])

==================================================
outputs/logbert/bert_no_time/Integrated_fixed/WEB1/ratio_0.8/seq_len_256/r_seed_31
==================================================
cuda:0 cuda:0
Building Vocab

100%|██████████| 4688/4688 [00:00<00:00, 23114.14it/s]

VOCAB SIZE: 60

Processing normal test data: 100%|██████████| 293/293 [00:00<00:00, 2415.83it/s]
Processing abnormal test data: 100%|██████████| 477/477 [00:00<00:00, 2498.23it/s]
100%|██████████| 4/4 [00:00<00:00,  5.14it/s]
100%|██████████| 477/477 [00:02<00:00, 172.22it/s]

Saving test normal results
Saving test abnormal results
[seq_th, FP, TP, TN, FN, Precision, Recall, F1, TPR, FPR]
threshold=0.000['53.0000', '142.0000', '203.0000', '335.0000', '72.8205', '29.7694', '42.2619', '29.7694', '20.7031']
threshold=0.010['27.0000', '76.0000', '229.0000', '401.0000', '73.7864', '15.9329', '26.2069', '15.9329', '10.5469']
threshold=0.020['7.0000', '39.0000', '249.0000', '438.0000', '84.7826', '8.1761', '14.9140', '8.1761', '2.7344']
threshold=0.030['6.0000', '28.0000', '250.0000', '449.0000', '82.3529', '5.8700', '10.9589', '5.8700', '2.3438']
threshold=0.040['6.0000', '25.0000', '250.0000', '452.0000', '80.6452', '5.2411', '9.8425', '5.2411', '2.3438']
threshold=0.050['5.0000', '24.0000', '251.0000', '453.0000', '82.7586', '5.0314', '9.4862', '5.0314', '1.9531']
threshold=0.060['4.0000', '21.0000', '252.0000', '456.0000', '84.0000', '4.4025', '8.3665', '4.4025', '1.5625']
threshold=0.070['3.0000', '18.0000', '253.0000', '459.0000', '85.7143', '3.7736', '7.2289', '3.7736', '1.1719']
threshold=0.080['3.0000', '15.0000', '253.0000', '462.0000', '83.3333', '3.1447', '6.0606', '3.1447', '1.1719']
threshold=0.090['2.0000', '13.0000', '254.0000', '464.0000', '86.6667', '2.7254', '5.2846', '2.7254', '0.7812']
threshold=0.100['2.0000', '11.0000', '254.0000', '466.0000', '84.6154', '2.3061', '4.4898', '2.3061', '0.7812']

### Integrated2 (T1105)
- 自前ログを入れたら精度が落ちた

In [ ]:
# train
main.main_cli([
    "train",
    "bert/Integrated2_T1105_fixed",           # conf/bert_config_name.yaml
    #"default.device_id=0",        # ここに好きな key=value を並べる
    #"default.epochs=10",
])

In [ ]:
# テスト
main.main_cli([
    "test",  # run_mode
    "outputs/logbert/bert_no_time/Integrated_fixed/T1105/ratio_0.8/seq_len_256/r_seed_31/weights/ValTotalbest.pth", # 重みファイルまでの相対パス
    "64",   # eval_batchsize
    "cuda:0",     # gpu
])

==================================================
outputs/logbert/bert_no_time/Integrated2_fixed/T1105/ratio_0.8/seq_len_256/r_seed_31
==================================================
cuda:0 cuda:0
Building Vocab

100%|██████████| 4688/4688 [00:00<00:00, 26546.98it/s]

VOCAB SIZE: 60

Processing normal test data: 100%|██████████| 353/353 [00:00<00:00, 1253.70it/s]
Processing abnormal test data: 100%|██████████| 13/13 [00:00<00:00, 2516.66it/s]
100%|██████████| 5/5 [00:00<00:00,  9.69it/s]
100%|██████████| 13/13 [00:00<00:00, 39.63it/s]

Saving test normal results
Saving test abnormal results
[seq_th, FP, TP, TN, FN, Precision, Recall, F1, TPR, FPR]
threshold=0.000['18.0000', '6.0000', '302.0000', '7.0000', '25.0000', '46.1538', '32.4324', '46.1538', '5.6250']
threshold=0.010['15.0000', '4.0000', '305.0000', '9.0000', '21.0526', '30.7692', '25.0000', '30.7692', '4.6875']
threshold=0.020['12.0000', '0.0000', '308.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '3.7500']
threshold=0.030['12.0000', '0.0000', '308.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '3.7500']
threshold=0.040['11.0000', '0.0000', '309.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '3.4375']
threshold=0.050['11.0000', '0.0000', '309.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '3.4375']
threshold=0.060['10.0000', '0.0000', '310.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '3.1250']
threshold=0.070['9.0000', '0.0000', '311.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '2.8125']
threshold=0.080['9.0000', '0.0000', '311.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '2.8125']
threshold=0.090['9.0000', '0.0000', '311.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '2.8125']
threshold=0.100['6.0000', '0.0000', '314.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '1.8750']

### Integrated (T1105)  ：bert_pretrained
- 全然ダメ。

In [ ]:
# train
main.main_cli([
    "train",
    "bert/bert_pretrained",           # conf/bert_config_name.yaml
    #"default.device_id=0",        # ここに好きな key=value を並べる
    #"default.epochs=10",
])

In [9]:
# テスト
main.main_cli([
    "test",  # run_mode
    "outputs/logbert/bert_pretrained/Integrated_fixed/T1105/ratio_0.8/seq_len_256/r_seed_31/weights/ValTotalbest.pth", # 重みファイルまでの相対パス
    "64",   # eval_batchsize
    "cuda:0",     # gpu
])

==================================================
outputs/logbert/bert_pretrained/Integrated_fixed/T1105/ratio_0.8/seq_len_256/r_seed_31
==================================================
cuda:0 cuda:0
Building Vocab

100%|██████████| 4688/4688 [00:00<00:00, 22803.30it/s]

VOCAB SIZE: 60

Processing normal test data: 100%|██████████| 353/353 [00:00<00:00, 2486.88it/s]
Processing abnormal test data: 100%|██████████| 13/13 [00:00<00:00, 2280.75it/s]
100%|██████████| 5/5 [00:00<00:00,  6.54it/s]
100%|██████████| 13/13 [00:00<00:00, 20.74it/s]

Saving test normal results
Saving test abnormal results
[seq_th, FP, TP, TN, FN, Precision, Recall, F1, TPR, FPR]
threshold=0.000['15.0000', '2.0000', '305.0000', '11.0000', '11.7647', '15.3846', '13.3333', '15.3846', '4.6875']
threshold=0.100['3.0000', '0.0000', '317.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.9375']
threshold=0.200['3.0000', '0.0000', '317.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.9375']
threshold=0.300['3.0000', '0.0000', '317.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.9375']
threshold=0.400['3.0000', '0.0000', '317.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.9375']
threshold=0.500['0.0000', '0.0000', '320.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=0.600['0.0000', '0.0000', '320.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=0.700['0.0000', '0.0000', '320.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=0.800['0.0000', '0.0000', '320.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=0.900['0.0000', '0.0000', '320.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']
threshold=1.000['0.0000', '0.0000', '320.0000', '13.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']